- README-en.md
- README.md
360云盘服务将于2017年2月1日正式关闭。
快盘个人存储服务已经于2016年8月16日正式关闭。
> 去除360云盘和快盘

- README-en.md
Currently redirects to author's another app.
The fix links to Tincta in AppStore.
> Fix broken Tincta URL

- README-zh.md
- README.md
The Skim pdf reader's link points to the CHM reader's homepage (http://www.hewbo.com/chm-reader.html). I fixed the link to point to the right place (http://skim-app.sourceforge.net/).
> Fix Skim urls

- README-zh.md
In README-zh.md:
> Veertu - 图片管理，用于图片研究。
In README.md:
> Veertu - The lightest VM on Mac. A responsive, sandboxed & native way to run VM on your Mac.
事实上英文中对 veertu 的介绍就不准确，veertu 其实是集成了 **[xhyve](https://github.com/mist64/xhyve) 虚拟机**的一套开发者工具。而这句介绍放在 xhyve 上就很合适。
所以我打算开个issue，请求添加 xhyve。
> 修正了 veertu 简介的翻译错误

- README.md
There was a typo in links for `micro` so the icons were displayed incorrectly.
> Fix a typo in icons for micro

- README-zh.md
- README.md
The listing for Vim is missing an OSS icon.
This PR adds that icon (as well as a link to the vim github repo: https://github.com/vim/vim) to both readmes.
My text editor adds a trailing newline to all files that I write so it has modified the bottom of the zh markdown file, I can remove this newline if it is not desired.
> add oss icon beside vim

- README.md
SensibleSideButtons adds the backward/forward functionality for side mouse buttons from Windows.
SensibleSideButtons is open-source (obviously) and adds a very useful feature from Windows, the ability to move forward and backwards in many apps using the side buttons on a mouse. By default, side buttons behave as a broken middle click in macOS.
> Add SensibleSideButtons

- README.md
1. The anchor to the command line tool sections is broken. It needs a `-` at the end due to the image at the end of the heading.
> Fix command line tools anchor

- README.md
In `README.md` which written in English, Visual Studio Code is positioned at IDE list. At official FAQ, they mentioned as below:
> Visual Studio Code is a streamlined code editor with support for development operations like debugging, task running, and version control. 
So I think VSCode should be moved to text editor list.
And I also checked on Chinese version. At there, VSCode is positioned at right place. So I updated English version also.
---
1. If you're adding something to the list, be …
> Move Visual Studio Code from IDE to Text Editor

- README.md
Adds Microsoft To-Do App to the list. Should be added because:
- it's new as a native Mac OS App
- Microsoft's successor to Wunderlist
- It's free to use
> Add Microsoft To-Do to Utilities/To-Do Lists

- README.md
Microsoft released MS Edge today. This is the official release of the new Chromium based browser.
1. This is simply a change to the Edge Canary  entry which was a preview of the new Edge based on Chromium.
2. Remove Yummy FTP. Yummy FTP's owner passed in 2018. No longer maintained.
3. Fixed multiple broken links. 
Main change was to add the …
> Remove Edge Canary and Replace with Edge, Fix dead links, Remove Yummy FTP

- README.md
freeVPN (https://www.freevpn.pw/en/) doesn't exist anymore. There is another app named VPN Plus (https://www.tigervpn.com/vpn-for-mac) made by TigerVPNs, that's linked to Mac App Store (https://apps.apple.com/us/app/vpn-plus/id1202726435), but it seems like they're were never the same.
I've removed the "freevpn.pw" link and switched it for the app (non-free) provided by this tigerVPN guys. I've removed the "free" badge as well. 
Finally -- and more importantly -- I've renamed the app name, since it doesn't exist anymore.
> Removes freeVPN as longs as it doesn't exist anymore

- README.md
Update url of linked because it moved from https://github.com/muc-dev/linked to https://github.com/lostdesign/linked
> Update url of linked

- README.md
Added the actual Keepass application, `keepassxc` to the list of password managers.  Its what many of the other password managers advertise as supporting its format, its what I use personally, and its installable via homebrew cask - its crazy that its not already on this list.
If this is a relatively large or complex change, kick off the …
> Lots of 'compatible with', but Keepass itself is not in this list

- README.md
The built-in macOS color picker is familiar to most users, but usually you would only be able to access it in certain apps. I made an app that includes the built-in color picker, but also adds lots of extra features, like quick copy to Hex, HSL, RGB, etc, keyboard shortcuts, color history, you can use it as a menu bar app or normal app, and many more features. The app has become quite popular (100+ ratings with 4.9/5 average).
https://github.com/sindresorhus/System-Color-Picker
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about …
> Add System Color Picker

- README.md
The built-in [Shortcuts](https://9to5mac.com/2021/06/20/macos-monterey-shortcuts-app/) app is very useful for automating things. However, there are many essential actions that it lacks. This app provides the missing pieces, making it easier to create shortcuts. This app solves a lot of problems for people using Shortcuts, which is a lot of users. You can think of this app as a toolbelt for Shortcuts.
You can see the reception to the app here: https://www.reddit.com/r/shortcuts/comments/qrp73j/useful_utilities_for_your_shortcuts/
Put an x in the boxes once you've completed each step. You can also fill these …
> Add Actions

- README.md
Adds Sequel Ace which I believe is a better option than Sequel Pro which according to Github was released last time in 2016. Sequel Ace is actively contributed to, seems stable and seems to just about the same as Sequel Pro.
Might want to consider removing Sequel Pro. Let me hear your thoughts if so.
> Add Sequel Ace

- README.md
[FinderFix](https://synappser.github.io/apps/finderfix/) is a purposefully simple one-job app that lets you open every new Finder window in the exact same position and size you want it to. It finally brings a lasting solution to Finder's notorious problem of reverting those windows back to a different (often microscopic) size the next time you open them.
Additionally, with the announced demise of TotalFinder on January 10, 2021, some of its essential features are being ported to FinderFix. It’s not yet a full replacement for TotalFinder but it already has some of its basic features without compromising the System Integrity Protection (SIP) which, by the way, rang the death knell for TotalFinder.
> Add FinderFix

- README-zh.md
- README.md
[CubicBezier](https://github.com/isaced/CubicBezier) is a Bezier curve generator widget for macOS, which can intuitively drag small dots to adjust parameters and compare through animation previews, which is convenient for us to write animations. (like [cubic-bezier()](https://www.w3schools.com/cssref/css3_pr_transition-timing-function.asp) / [CAMediaTimingFunction](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Animation_Types_Timing/Articles/Timing.html))
Open source, and you can download it for free in the [AppStore](https://itunes.apple.com/us/app/cubicbezier/id1228492117?l=zh&ls=1&mt=12).
> Add CubicBezier

- README.md
> MacYTDL - https://github.com/section83/MacYTDL
Some key features:
* Download individual videos and playlists.
* Download multiple videos separately (in parallel) or in one process (sequentially).
* Can switch between _youtube-dl_ and _YT-DLP_ on Macs running macOS from 10.15 to 12.2.1.
* Can pass through any custom settings to _youtube-dl_ and _YT-DLP_.
* Settings for level of youtube-dl feedback, download folder, file format, remuxing format, download speed, proxy URL, custom file name template etc.
* Batch downloads.
* Optional macOS Service which gets the current text selection, clipboard contents or active web browser URL, switches to MacYTDL and pastes URL of video to be downloaded.
> Add MacYTDL

- README.md
> ActivityWatch - https://activitywatch.net/
ActivityWatch is an app that automatically tracks how you spend time on your devices. It is open source, privacy-first, cross-platform, and a great alternative to services like RescueTime, ManicTime, and WakaTime. It can be used to keep track of your productivity, time spent on different projects, bad screen habits, or just to understand how you spend your time.
> Add ActivityWatch

- README.md
> Cloudflare WARP - https://1.1.1.1/
1.1.1.1 with WARP replaces the connection between your device and the Internet with a modern, optimized, protocol. The WARP application uses [BoringTun](https://github.com/cloudflare/boringtun) to encrypt all the traffic from your device and send it directly to Cloudflare’s edge, ensuring that no one in between is snooping on what you're doing. If the site you are visiting is already a Cloudflare customer, the content is immediately sent down to your device.
https://blog.cloudflare.com/1111-warp-better-vpn/
https://blog.cloudflare.com/warp-for-desktop/
> Add Cloudflare WARP

- README.md
Pasting as plain text is what you usually want. This app makes it the default. It also has bonus features like removing tracking parameters from URLs.
**FAQ**
‣ Why not just use the “Paste and Match Style” menu item or “⌥⇧⌘V”?
- That menu item is not available in all apps.
- The keyboard shortcut is hard to remember and type.
- This app can exclude certain apps, preserve links, and also remove tracking parameters from URLs.
Put an x in the boxes once you've completed each step. You can also fill …
> Add Pure Paste

- README.md
Removing LastPass software in the password managers category.
The removal is due to maintaining the concept of the repository as "collect awesome macOS software in various categories". 
Due to the latest incidents involving user data, it is preferable not to consider this product, at least for the moment, as one of the "awesome" choices in its category.
More details:
[LastPass blog - Security Incident](https://blog.lastpass.com/2022/12/notice-of-recent-security-incident/)
[Wikipedia - Security incidents list](https://en.wikipedia.org/wiki/LastPass#Security_incidents)
[LasPass blog - Additional details of the attack](https://support.lastpass.com/help/incident-2-additional-details-of-the-attack)
> Removing LastPass from the list

- README.md
Mullvad Browser is a version of Tor Browser with Tor network integrations removed, aimed at providing Tor Browser's anti-fingerprinting browser technologies to VPN users. It is developed by the Tor Project and distributed by Mullvad, and does not require the use of Mullvad's VPN.
- *Also: fixed the OSS icon link for Tor Browser, since the git.tpo repo is no longer updated.*
> Add Mullvad Browser and fix Tor Browser OSS link

- README.md
qutebrowser is a keyboard-focused browser with a minimal GUI. It’s based on Python and Qt and free software, licensed under the GPL.
- Indent forks:
- Tor > Mullvad
- Firefox > Librewolf
- Chromium > ungoogled-chromium
> Add qutebrowser and indent forks

- README-zh.md
>  delete  虾米音乐

- README.md
It's an anti-forensic macOS tray application designed to safeguard your system or server by monitoring USB ports. It ensures your device's operational security by automatically initiating either a system shutdown or hibernation if an unauthorized device connects or a connected device is unplugged. It offers the flexibility to whitelist designated devices, to select an action to be executed and to set a countdown timer, allowing to disarm the shutdown process. It's a revival of the well-known [usbkill project](https://github.com/hephaest0s/usbkill) by hephaestos, but with a Graphical User Interface and added functionality.
For non-technical user, using the original usbkill command line tool (see above) is far too difficult. This is the reason for swiftGuard: It offers a nice, clean and …
> Add swiftGuard (Physical Access Security)

- .github/ISSUE_TEMPLATE/REMOVE_ITEM_FROM_LIST.yml
The removal template asks you to submit an app to be added to the list; this is obviously incorrect for a removal request.
Additional changes:
- updated label to "removal" instead of "addition"
- corrected the "app to remove" field asking you for your app "to add"
> chore: Modify removal suggestion template

- README.md
You should remove Skiff since they are defunct and shutting down service in 6 months.  See <https://skiff.com/data-migration>.
> fix: removed skiff (defunct and shutting down in 6 months)

- README.md
I would like to add Lasso to the list because users seem to love it (it has 4.9 rating on the[ Product Hunt](https://www.producthunt.com/products/lasso-window-wanager-for-macos/reviews?utm_source=badge-product_rating&utm_medium=badge&utm_souce=badge-lasso-window-wanager-for-macos)) and it's a more advanced version of a similar app called Divvy which is not maintained anymore and does not support modern Apple processors. The app is actively maintained, native, and has a nice and simple UI. Thanks for consideration.
> Add Lasso window manager

- README.md
MakeItHome is a UI extension for macOS. It’s been on the App Store for a year and a half, but it’s been open source for a short time. It's a pretty complex app to develop, and it's very useful and often essential if you used to use it. 
It need user base to continuing its development, mainly for feedbacks and motivations. Due to the lack of feedback, for the moment there are still common issues, that I'm fixing constantly. 
This adding to the list may be a lot important for the existence of the project, seen that due to the lack of trust of users and disillusion about the market, is pretty hard to obtain more than 1 download daily, even if it's a free app.
I really appreciate your support and I hope this …
> MakeItHome

- README.md
The app provides additional AI-related actions for the Shortcuts app. For example, an action to interact with the ChatGPT API.
How is this better than just calling the OpenAI API directly from Shortcuts? This makes it simpler, but more importantly, it stores your API key securely in the keychain. This means you can share your shortcuts to others without exposing your API key. The API key is not stored in the shortcut.
https://sindresorhus.com/ai-actions …
> Add AI Actions

- README-zh.md
change Coda's link to Nova's, since Coda is now Nova.
> fix: replace outdated link

- README.md
Needing to know the week number is a common need in Europe where it's used a lot. This puts the week number front and center, and also lets you quickly find the week number for a specific date.
https://sindresorhus.com/week-number
> Add Week Number

- README.md
I'm not sure if adding your own apps is allowed, but this pull request adds a project that I have been working on - CodeMenu. It's a snippets manager with many useful features. It has features like:
- a side window (it contains a list of snippets and filters and allows for drag and dropping, quickly running snippet's code and working with placeholders [either by pre-filling them or filling while copying by long-pressing a card])
- access in IDEs using Suggestions app
- natural language search
- placeholders (there are also advanced ones like shell, date and time too)
- code running and HTML preview
- online snippets database 
- useful programming tools (editor for running code, RegEx …
> Add CodeMenu

- README.md
Added x-cmd to the list, x-cmd is a toolset implemented using posix shell and awk.
It is very small in size and offers many interesting features. Here is a milestone demo: https://x-cmd.com/
**Tools Provided by x-cmd:**
- [Wrappers for Common Commands (e.g., cd, ip, ps, tar, apt, brew)](https://x-cmd.com/mod/zuz): These wrapped commands are more intelligent and easier to use compared to the native commands.
- [Lightweight Package Management Tool](https://x-cmd.com/pkg/): We have implemented a lightweight package management tool using shell and awk. Through it, you can quickly obtain most common software tools, such as jq, 7za, bat, nvim, python, node, go, etc.
- [CLI for Useful Websites (e.g., github.com, cht.sh)](https://x-cmd.com/mod/cht): We have wrapped their APIs using shell and awk …
> Add x-cmd to the Command Line Tools list.

- README.md
Although perhaps a radical change, I think replacing Cakebrew with Cork is warranted. Cakebrew has been abandoned for three years, so it's no longer getting updates and support, and is likely to break with upcoming Homebrew updates. Cork, on the other hand, is in active development, is the same type of app, and supports the same features Cakebrew does.
As for the app itself, it's a GUI for Homebrew. It supports all Homebrew features, including:
- Formulae and Casks
- Taps
- Installing, updating and pinning packages
- Homebrew services
- Full support for `sudo` operations.
It also supports extra features:
- Automatically respecting the system proxy
- Tagging of packages
- Custom …
> Replace Cakebrew with Cork

- README-zh.md
Since Google has shut down this service, the repository author has archived it, so the outdated content is being removed.
> Remove Radiant Player & Add Comic2Books, Applite, Altstore to Chinese list & fix bugs

- .vscode/settings.json
- README-zh.md
- Removed: iFFmpeg, Soda Player, Sonora, 零信, 今目标, RTX_腾讯通, Yomail, AlloyDesktop, Adium Messenger
- Added: 1.1.1.1, escrcpy, PopClip, MonitorControl, Mastodon, Signal, sing-box, Matrix, 企业微信, Microsoft Teams, Chrome Remote Desktop, lima-vm, PDFgear to Chinese list
- Fixed various bugs
> Remove 8 apps & add 12 apps to Chinese list & fix bugs

- README.md
**Airlift**
Airlift draws inspiration from our very own [CSV2Notion Neo](https://github.com/TheAcharya/csv2notion-neo), which was inspired by Airtable’s [CSV import extension](https://support.airtable.com/docs/csv-import-extension). And with Airlift, we have come full circle.
To send data to Airtable, users or applications need to write custom code using libraries that connect with Airtable's API. For normal end-users who aren’t developers, this can be an extremely challenging endeavor. For most …
> Added Airlift, CSV2Notion Neo & MarkersExtractor

- README.md
Adding [RecurseChat](https://recurse.chat/) to the list since it offers unique value to users seeking a privacy-focused AI chat experience 😊. It's a local-first chat application with AI that prioritizes user privacy while providing powerful customization options. Some standout features:
- Personal and private: Runs locally on your machine, keeping your conversations secure
- Simple yet powerful interface: Clean design with extensive customization options
- Fast performance: Optimized for quick responses and smooth interaction
- Local-first architecture: Works offline and keeps your data under your control
The app fills an important niche for users who want the benefits of AI chat while maintaining control …
> Add RecurseChat

- README.md
Launchy is an app launcher and switcher for macOS. It is designed to enhance productivity through a customizable and visually appealing radial menu interface. Launchy allows users to quickly launch and switch between apps using keyboard shortcuts or mouse gestures, making it perfect for both casual and power users.
I think Launchy deserves to be added because it offers a unique, streamlined alternative to traditional app launching methods like the Dock or Spotlight, with a focus on ease of use, customization, and speed.
AppStore link: [https://apple.co/3PLI2AH](https://apple.co/3PLI2AH)
> Add Laucnhy app

- README.md
- command-line-apps.md
There were several terminal emulators in the `command-line-apps.md` file making them difficult to find. I've moved them to the [`Terminal Apps`](https://github.com/jaywcjlove/awesome-mac/blob/master/README.md#terminal-apps) section in the main README. In addition to moving the links, the section was made to adhere to the alphabetic ordering rules. Links were only moved, not added or removed.
This commit does not update the Chinese language versions of files.
1. If you're adding something to the …
> Organize terminal emulators under `Terminal Apps`
