jaywcjlove/awesome-mac

README.md

fix: 修复中州韻輸入法引擎网址错误问题

---

README.md

修复Mac玩儿法链接

---

README.md

+ 添加 typora

---

README-en.md

`Developer tools`部分翻译, 部分直接参考了软件官网的描述.

`Developer tools`部分翻译

---

README-en.md

翻译正则表达式编辑器, 测试工具和命令行工具

---

README-en.md
README.md

Translate communication and data recovery section to English
Recommend a VPN provider

Translate two sections, recommend a VPN provider

---

README-en.md
README.md

新增Email客户端, Markdown编辑器. 解决冲突.
冲突是因为别人的PR先合并掉了, 都是基于同一个版本的代码在改.

新增Email客户端, Markdown编辑器. 解决冲突

---

README-en.md
README.md

MongoBooster是MongoDB的图形化管理软件, 内嵌MongoShell, ES6语法，流畅查询接及智能感知.
帮忙给加一下，谢谢！
注：我是该工具的主要开发人员

add database tool MongoBooster

---

README-en.md
README.md

分享3个自己喜欢且经常用的插件／软件：
* fish shell
* oh-my-fish (package manager for fish shell)
* Solarized
分别修改了中文版本和英文版本

加几个比较喜欢的插件

---

README-en.md

Adds LightTable to Editors list

Adds LightTable to Editors list

---

README-en.md
README.md

修改了telegram的描述，增加了一款比较火的网络富媒体下载工具 (支持youtube，b站等)。

modify telegram's description and add you-get download tool.

---

README-en.md
README.md

wonderful [Electron](http://electron.atom.io/) based multi protocol chat client
plus two descriptions in english

feat(chat): Franz, One application, 23 messenger services

---

README-en.md
README.md

add Reggy's link

---

README-en.md

Add Mega (Online Storage), Vivaldi (Web Browsers), InsomniaX (Utilities), Spectacle (Window Management), MockFlow (Prototype Workflow)

Add Mega, Vivaldi, InsomniaX, Spectacle, MockFlow

---

README-en.md
README.md

一个很适合程序员的`menu bar`工具.
有不少已经做好的插件, 也可以自己开发. 目前支持很多语言.

refactor: 新增其他工具 BitBar

---

README-en.md

**DO NOT MERGE**
**请勿Merge**
> Everything before `Reading and Writing` is reviewed
> TODO: Will add `KeyCastr` to the list.
> TODO#2: Will try to categorize **Utilities**
> TODO#3: Will add my config file for `HammerSpoon`. Just finished a window management config file. Here is the [link](https://github.com/S1ngS1ng/HammerSpoon).
* General
* Check links URL, make sure it works
* Update some URL, redirecting to English website
* Check if the app comes with English UI and English Docs
* Update description according to official website
* **Editors**
* Change header to `Editors and IDE`
* Move `Intellij IDEA` and `WebStorm` here
* Add plugins recommendation for WebStorm, add `Free for Educational Use` info
* Add `linter-eslint` to Atom plugins
* **Other Tools**
* Add `Snagit`, which is my …

Review and update of README-en.md before ## Reading and Writing

---

README-en.md

* Split `Editor and IDE` into separate parts
* Remove `Kuaipan` as service is no longer provided by Kingsoft
* Verify all URLs before `##Web Browsers`, update description according to official website

Review and update README-en.md before ## Web Browsers

---

README-en.md

* Apps I added:
* KeyCastr
* Fantastical, Things, OmniFocus, 2Do, Wunderlist
* Divvy, SizeUp
* Move `tmux` to `## Command Line Tools`
* Reformat `Utilities` part, add detailed categories
* Rewrite `Get Apps`, `Black-list` and `Something Useful`

Final commit for README-en.md

---

README-en.md

Add itunes-remote to the CLI section

---

README-en.md

@jaywcjlove Please take a look 😃

Added Clip Menu - a general productivity tool

---

README-en.md

@jaywcjlove Hey please take a look 😃

Added Stellar Phoenix - A powerful data Recovery tool

---

README-en.md

A utility app which prevents the mac from going to sleep with a single click.
@jaywcjlove Please take a look 😃

Added Caffeine - A utility app

---

README-en.md

Added Tincta - A text editor for OS X

---

README-en.md

@jaywcjlove Please take a look 😃

Added R-Studio, A powerful recovery tool

---

README.md

Fixed couple typos in Chinese text, and replaced half-width commas with full-width ones to make formatting consistent.

Fix typos in Chinese README.md

---

README.md

- Remove trailing spaces after full-width period
- Normalize terms
- Remove residual original English texts
PS: Sorry about my OCD :stuck_out_tongue_closed_eyes:

More formatting

---

README-en.md

@jaywcjlove Please take a look 😃

Added Balsamiq mockups - A rapid wire framing tool

---

README-en.md

Added NetBeans IDE - A open source IDE for OS X

---

README.md

add Cmd Markdown

---

README-en.md

Principal, Vectr, Orioki, MJML App

added several new apps

---

README.md

添加 协作工具 日事清

---

README-en.md
README.md

Thanks a lot for this amazing collection guys!

Fixed the links to the MJML Github on the Chinese and English READMEs

---

README-en.md

MagicaVoxel is a popular and free lightweight 8-bit voxel editor and interactive path tracing renderer.

Adds MagicaVoxel under "Design Tools"

---

README.md

Thanks to reddit user [Felixwu](https://www.reddit.com/user/Felixwu) for the translation. Hopefully this helps!

Added NetBeans translation on Chinese README.md

---

README-en.md
README.md

Add tree-view-search-bar

---

README-en.md
README.md

Thanks for making great curation list!
Please take a look :)

Add Inkdrop under "Reading and Writing"

---

README-en.md

Also use the proper casing for it.

Remove duplicate mpv

---

README-en.md
README.md

update spechtlite + sparkmail

---

README-en.md

typo readme.md

---

README-en.md

Marked 2 is an awesome Markdown previewer.  Great for people that already have a preferred way of editing Markdown, but want to get a live preview of the document they are working on.

Add Marked 2 in Markdown section

---

README.md

Focus is a well-designed Pomodoro app for Mac OS that I highly recommend!
https://masterbuilders.io

Add Focus (Pomodoro App)

---

README.md

KeepingYouAwake is a better alternative to Caffeine and supports darkmode for the bar menu (which Caffeine do not). Also it is open source.

Adds KeepingYouAwake. Better Caffeine alternative

---

README.md

Coolant is a menubar app that lets you know when an app is consuming 100% CPU or more than a gigabyte of memory (or any arbitrary limits you choose).

Add Coolant to 'System Related' section

---

README.md

Open-source NextCloud platform for creating file hosting services and using them.

Online Storage - NextCloud

---

README.md

Hi, I really need this feature on my Mac, so I make it. Hope it is useful to other people too

Add FinderGo

---

README.md

Fixed several spelling / grammar issues, also tried to reword some phrases so they make more sense in English.

Spelling and grammar fixes in README

---

README.md

Hey!
Thank you for maintaining this awesome list of applications and tools.
Cheers

Add james proxy

---

README-zh.md
README.md

这个工具可以在一定程度上取代Charles。
[mitmproxy套件使用攻略及定制化开发](http://www.freebuf.com/sectool/76361.html)
[使用 mitmproxy 监控 HTTP 请求](http://liuxiang.logdown.com/posts/192057-use-mitmproxy-to-monitor-http-requests)

Add mitmproxy

---

README.md

Mongotron APP: A Mongo DB GUI built using Electron, and Angular Js.

Add Mongotron APP

---

README-zh.md

lighttable.com not support HTTPS

Update URL of LightTable

---

README-zh.md
README.md

Fix Wrong link for [Fork](https://git-fork.com/) Git GUI, it must be https://git-fork.com/

fix Fork link

---

README.md

Hey, just wanting to add TunnelBear to VPNs list. Great VPN service I've found useful. Thanks!

Add TunnelBear to VPNs

---

README.md

Updated several application descriptions so they are more accurate or provide more information.

Adjusted descriptions and formatting on English README

---

README.md

Updated English descriptions in the following sections:
Proxy and VPN Tools
Online Storage
Download Tools
Frameworks for Hybrid App
Reading and Writing
Audio and Video
Data Recovery
Email
Communication
Virtual Machines
Other Tools

Style, wording and description updates

---

README.md

Updated the following sections:
Prototype Workflow
Design Tools
Database
Version Control System
GUI
Version Control
Command Line Tools
Test Tools
Regular Expression Editors
There were a few other style changes scattered throughout the document.

Updated descriptions and information in the English README

---

README.md

The cool-retro-term project is already listed on line 157 under the heading 'cool-retro-term'.

Removed duplicate cool-retro-term listing

---

README.md

Also changed several of the document headers so they use a plural wording.

Updated application descriptions and header formatting

---

README.md

Let me know if you need any changes to this.

Added Android Studio under the IDEs category

---

README-zh.md
README.md

Add two video tools:
- Aegisub: subtitle editor
- iFFmpeg: video encoding tool

Add video tools

---

README.md

Added bear to the Utilities > Productivity section. Bear is a beautiful, flexible writing app for crafting notes and prose available as both as free and pro versions.
[http://www.bear-writer.com/](http://www.bear-writer.com/)

Add Bear Writer to Utilities > Productivity

---

README.md

I didn't feel comfortable copy pasting descriptions for translations, sorry that's missing from my PR.

A few big players are missing =)

---

README.md

better descriptions that reflect unique features of the apps

added Pixel Perfect, updated Newton, Qbserve, Scapple

---

README.md

Added Chromium to the Web Browser list - this is an open source web browser/project which provides the source code for google chrome. This web browser is particularly suitable to developers who have a passion for open-source software and want a light - fast web browser.

Added Chromium to the Web Browser list.

---

README-zh.md
README.md

Hi,
I'm author of [Klib](https://en.toolinbox.net/Klib/), [iPic](https://en.toolinbox.net/iPic/), [iPaste](https://en.toolinbox.net/iPaste/) and [iHosts](https://en.toolinbox.net/iHosts/). Just update the Mac App Store link. Welcome to merge.
BR,
Jason

Update MAS link for Klib, iPic, iHosts, iPaste.

---

README.md

I want to add own application. Keylord is a desktop GUI client for Redis, Bolt, LevelDB and Memcached key-value databases.

Add Keylord application

---

README-zh.md
README.md

add Yomail

---

README-zh.md
README.md

Edited for both English and Chinese. 
- Renamed `robomongo` to `Robo 3T`
- Fixed a few typo
- Add DBeaver for Database

Fix typo and add for Databases

---

README.md

Vanilla is a great little utility from an active developer. It has a free version and a premium version, but the free one does everything you'd need.
http://vanilla.matthewpalmer.net
Hide menu bar icons on your Mac.

Add Vanilla

---

README.md

Couleurs is a nice small utility for grabbing screen colors. It supports plenty of color formats and is super simple to use.
Couleurs is a simple app for grabbing and tweaking the colors you see on your screen.
http://couleursapp.com

Add Couleurs

---

README.md

I added the Figma app in the Design Tools section
Website: [figma.com](https://figma.com)

Added Figma in the design tools

---

README.md

Add Visual Studio Community for Mac to the IDE section.

Add Visual Studio Community for Mac

---

README.md

The Keybase app:
has built-in encrypted chat, for teams and DM's
has built-in encrypted filesharing
gives you crypto commands in your command-line
is open source

Add Keybase

---

README-zh.md
README.md

add Termius

---

README.md

I have added a new tool that is useful for offline browsing of websites. It's basically useful for one time download of website to localhost and viewing it offline.

Added a new tool under utilities  section

---

README-zh.md
README.md

and https://www.firefox.com/ as http://www.firefox.com.cn/
迎接全新的 Firefox Quantum。快而不俗。

 Meet Firefox Quantum

---

README.md

Hi, I'm the author of LyricsX. The description on MAS is just for cheating on Apple, please use the description on GitHub.

revise the description of LyricsX

---

editor-plugin-zh.md
editor-plugin.md

Lightweight & Customizable Vim configuration options.

add 7th-vim, a Lightweight & Customizable Vim configuration options.

---

README-zh.md
README.md

* 修正 Surge 的網址
* 移除 Surge Freeware Icon
* 增加 App Store 連結

Fix Surge Url

---

README.md

- Upterm is a terminal based on electron and black screen and when clubbed with oh my zshell it becomes extremely powerful.
- Added it under Command Line tools

added upterm under command line tools

---

README-zh.md
README.md

2 Insomnia links in same section.

Remove duplicate

---

README-zh.md
README.md

添加项目管理软件OminPlan

---

LICENSE
README-zh.md
README.md
contributing.md

Deals with item 3 of https://github.com/jaywcjlove/awesome-mac/issues/330.

Deals with item 3 of #330.

---

README-zh.md

Removed duplicate rishiqing entry.

Removed duplicate rishiqing entry

---

README-zh.md

Just read the comment asking for further changes on this PR. reverting

Revert "Removed duplicate rishiqing entry"

---

README-zh.md

Remove the duplicated entry and fix the comma in Chinese version.

Remove duplicate entry and fix comma in Chinese version

---

README.md

add ack && archey && ccat

---

contributing.md

Updated Contributing.md

---

README.md

Added http://totalspaces.binaryage.com/
Added Total Spaces to the windows management list
Total Spaces helps you management workspace much like Ubuntu. However, their marketing is extremely poor.  …

Update readme.md - Windows Management section

---

README.md

Added some missing hyphens between the app name/app website and description. Additionally, one dash was replaced with a hyphen, and a misplaced link was removed.

Add some missing hyphens

---

README.md

fix gitfinder link

---

README.md

- Add line breaker for symbols of README.md
- It seems to be more readable as README-zh.md

Add line breaker for symbols of README.md

---

README.md

- Renamed the SubSection "Utilities" of the section "Reading and writing tools" to "Others" because Utilities is not such a good name. Another reason is that there is a section called "Utilities" allready and so the anchor of the table of contents link both to the first entry.
- Fixed the anchor of the subsection "API Development and Analysis" which was broken.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for …

Fixed ToC Entries

---

README.md

MPlayerX's most recent update includes a Malware installer that asks for your Mac admin password.
For more info: https://blog.malwarebytes.com/threat-analysis/2016/09/pup-friday-mplayerx/
Or on Mplayer (original project) blog: http://mplayerhq.hu/design7/news.html

Remove MPlayerX

---

README.md

* [Docker](https://www.docker.com/) - Powerful, performs operating-system-level virtualization.
- [Wikipedia](https://en.wikipedia.org/wiki/Docker_(software))
- [ZDNet Article](https://www.zdnet.com/article/what-is-docker-and-why-is-it-so-darn-popular/)
Docker is hotter than hot because it makes it possible to get far more apps running on the same old servers and it also makes it very easy to package, virtualize and ship programs.

Add: Virtualization - Docker

---

README.md

I've added TG Pro (https://www.tunabellysoftware.com/tgpro/) which I believe is worthy of being on the awesome list since it's one of the best fan control and temperature monitoring apps for macOS. It supports all Mac models and displays more temperatures sensors than other apps due to the extensive R&D that went into making the app. **The reason I'm proposing to add it to the list is it's a valuable tool to help extend the life of people's Macs by cooling down the components and allowing them to monitor all the internal temperatures (ex: CPU, GPU, HD, Memory, etc). It allows people to be proactive in …

Added TG Pro

---

README-zh.md
README.md

Remove DLite
The project is abandoned and the lasest update was made 2 years ago + now we have the 'officia'l way to run Docker on mac (Docker for Mac).

Remove DLite

---

README.md

When I was looking for a nice but advanced clipboard manager, I settled on this one (there were only a few matching apps).
It's written by a reliable developer and has a nice UI with many advanced features (sequential paste, filters, many pasteboards, and customizations)

Add PasteBot

---

README.md

In comparison to finicky, this app has a user-friendly UI and browser extensions

Add Choosy

---

README.md

A nice app that allows you to check words, phrases, and sentences (supports wildcards) against existing text bases like The New York Times, Encyclopedia Britannica and etc.
It's a clean version of #383 (properly capitalized and without the accidental English link change)

Add Ludwig

---

README-zh.md
README.md

It's outdated, not supported anymore and was replaced by Amphetamine

Remove Caffeine

---

README.md

Amphetamine is the successor of Caffeine

Add Amphetamine

---

README-zh.md
README.md
editor-plugin-zh.md
editor-plugin.md

Resolve #389 Trimming Badge Selection

---

README.md

This is a super tiny fix. But it's matter of fact. …

Dash is not freeware

---

README.md

**It is a useful tool to prevent people from closing applications by mistake.**
If this is a relatively large or complex change, kick off the discussion by explaining …

Add SlowQuitApps

---

README.md

Add MarkText

---

README-zh.md
README.md

1. [contexts](https://contexts.co/) : Radically simpler & faster window switcher. if you have multi screen, it can help you to focus on your work space.
- [X ] New addition to list
1. [contexts](https://contexts.co/) : Radically simpler & faster window switcher. if you have multi screen, it can help you to focus on your work space.

 ### add  multi screen  manager tool : contexts

---

README.md
editor-plugin.md

Resolves #392
Remove items with no English docs/UI and locale-specific items. Changes all links to corresponding English versions

Resolve #392

---

README-zh.md
README.md

- Add Dockstation, it's a Mac Application with beautiful UI.
- Add Portainer, a web UI which supports batch operation for Docker images, containers, volumes, stacks, networks. And it allows remote control for docker machines.
Overall both tools are awesome and active maintained.
- Add Chinese version Docker
- Fix style issues (trailing spaces) …

Add Dockstation, Portainer, and Chinese version Docker

---

README-zh.md
README.md

The project is abandoned and there are other KeePass compatible alternatives (including the official one)

Remove KeePassX

---

README-zh.md
README.md

Cloud-based password manager with award-winning design, one of the top players.

Add Dashline

---

README.md

There were double spaces and trimmed recently in a not formatting-related commit. I guess it was done by accident.

Fix line brakes in the icon legend list

---

README.md

Add Podcasts section
Some lists include sections for books, podcasts and etc ... (like this one includes links to app stores and discussion sites).
Would be nice to have a podcasts section here, especially taking into account that many Apple related podcasts are analytical and mainly discuss rumors.
Mac Power Users is a productivity-oriented one. They discuss applications, MacOS, tips, work and integration with other Apple devices, interview …

Add Podcasts section

---

README.md

Closed source with multiple serious security vulnerabilities discovered
in the past.
Closed source with multiple serious security vulnerabilities discovered
in the past. 
https://news.ycombinator.com/item?id=15776964 …

Removed Remembear

---

README.md

As I said in the commit comment, I think it is a pretty neat tool for the menu bar. There is a similar paid tool called iStat. Because I couldn't find a free alternative, I decided to make one for free. And since I think it can be useful for a lot of people, I would be happy to see it on the list :)
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply …

Added iGlance

---

README.md

It's abandoned (the latest beta doesn't work with the previous version of MacOS (Sierra)). And 1.0 is not available (+ it's paid) so there is no way to try it

Remove Mou

---

README.md

Nice app that helps you to keep your battery healthy. It's quite popular and has a lot of good feedback

Add FruitJuice

---

README.md

1. Update brackets description.
1. Move non IDEs from IDEs section. 
1. Remove WebStorm plugins - the list wasn't full and if try to make it full the section will be really bloated
1. Add Toolbox app and organize all JetBrains IDEs under it
1. Add GoLang IDE
1. Update Deco IDE link to a new one
1. Update IntellJ description - the site suggests that it's an IDE for not only Java.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we …

Reorganize IDEs

---

README.md

Nice, and probably, the only haskell IDE. Very useful for exploration purposes.
For some reason the app store name is different, but everywhere else its name is 'Add Haskell for Mac'
The description is copied from the site.

Add Haskell for Mac

---

README.md

Added Mac Cache cleaner

---

README.md

Joplin is a nice open source note taking and to-do application with synchronization capabilities. I really like the awesome Markdown support, the encrypted synchronization, the cross platform support and also the design.

Add joplin

---

README.md
editor-plugin.md

Generally, if an awesome list contains items from this repo then the items are removed and vice versa, exceptions:
* QuickLook plugins - some items aren't in the list but still removed from this repo because in that repo they were removed with a good explanation
* command line tools - didn't do any comparisons or changes because of structural differences, we need to think how to perform the merge
* markdown tool - the same structural differences
Future candidates for externalizing: mongo, mysql, postgre, zsh
Possible improvements: find or create another nice but less bulky icon
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about …

Resolve #431

---

README.md

Move Vagrant to Virtualization

Move Vagrant to Virtualization

---

README.md

Add emacs OSS and freeware icons

Add emacs OSS and freeware icons

---

README.md

It seems this item belongs to IDE section. It's nice to have all JetBrains IDEs under the same section because they share a lot of common things.
The description is updated according to the latest description on the official site

Move DataGrip to IDEs and update description

---

README.md

Move Cakebrew to Package Managers

Move Cakebrew to Package Managers

---

README.md

This PR adds Enpass to the Password Management list. Enpass is a cross-platform password manager with cloud integration. Desktop Apps are free.
Cheers

Add Password Management - Enpass.io

---

README-zh.md

chore(*): fix typo

---

README.md

LosslessCut is a tool used by many people for super fast rough processing of videos from cameras, drones etc
Guidelines say alphabetical so I added it accordingly, even though order is chaotic there.

Add LosslessCut

---

README.md

Add Sublime Merge app, release this month, available for macOS.
Enjoy the sublime!

Add Sublime Merge

---

README.md

Today needed to work with a big file (~20GB) and found that it is not that many hex editors for macOS. This one worked fine and it's from a reliable author.

Add Hex Fiend

---

README.md

Notion is a great note-taking app available for Mac, Windows, iOS, Android, and web. It's a definite addition to the notes category.

Adding Notion

---

README-zh.md
README.md

Add Setapp

---

README.md

Added CloudApp screen capture tool.
CloudApp is a fantastic screen grab tool. With it's easy of use and the fact that it takes advantage of native notifications and the touchbar makes it's adition a no brainer.

Added CloudApp

---

README.md

1. Fix some minor formatting by removing the extraneous square bracket after the Carbonite description …

Remove extra square bracket

---

README.md

- Remove Datum SQLite (page no longer exists)
- Fix Aurvan SQLight link
- Update Nik Collection link (change of ownership, no longer freeware)
- Fix Krita open source link
- Remove Bitpost (page no longer exists)
- Fix VOX Player link
- Fix Hydrogen link

Fix and remove links

---

README.md

1. Added Arq, a cloud backup client that supports Amazon Cloud Drive, Amazon Web Services (S3 or Glacier), Backblaze B2, Google Drive, Google Cloud Storage (including "Nearline"), Dropbox, OneDrive. …

Add Arq to Cloud Storage

---

README.md

Added Dozer to the list because it unclutters the menubar which gives MacOS a cleaner look. Also it is open source.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution …

Added Dozer

---

README.md

Add coconutBattery, which is a great tool to monitor and get some great statistics about your Mac battery status.

add coconutBattery to System Related Tools

---

README.md

1. Fix the quick look plugins link

Fix quick look plugins anchor link

---

README.md

1. I would recommend adding `bat` as a fantastic command line tool that behaves like a drop in replacement for POSIX `cat` but also adds a really nice syntax highlighting, git integration, and a general user friendly interface.
2. I would also recommend adding `the_silver_searcher` to the list as a great drop in replacement and alternative for `ack`, but with a very friendly and usable interface.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of …

Add `bat` and `ag` to the "command line tools section

---

README.md

Add trash to command line tools

---

README.md

Add Bartender

---

README.md

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you …

Added Password Management - Buttercup

---

README-zh.md
README.md

Woodpecker is a Mac app aimed at helping us develop iOS Apps efficiently.
It can helps us:
- view, modify sandbox files;
- monitor network request;
- view, modify UserDefaults item;
- run javascript code in webView;

Add Woodpecker to Developer Utility

---

README.md

1. Nozbe is a really nice app fully based on Getting Things Done methodology. Nozbe is available on all Apple devices. It is used by many "Productivity Gurus", like Michael Hyatt.
If this is a relatively large or complex change, …

Add Nozbe to To-Do List

---

README.md

Cacher is a code snippet organizer for pro developers and their teams. It is a cross-platform, cloud-based app used to curate a snippet library.
Features:
* Support for editing and viewing 100+ programming languages.
* Flexible color-coded labels to categorize snippets.
* Shareable snippet pages via Cacher's code-sharing community: [snippets.cacher.io](https://snippets.cacher.io)
* Team and organization features like shared libraries, notifications, role management and code reviews.
* Desktop clients for macOS, Windows and Linux.
* Full-featured web app: [app.cacher.io](https://app.cacher.io)
--- …

Adds Cacher - Code snippet manager

---

README.md

Added, https://github.com/rupa/z which is an easy way to navigate in the terminal. …

Add a productivity tool

---

README.md

Adds https://www.presetbrewery.com - a tool to convert Lightroom presets to Adobe Camera Raw, so that you can use them in Photoshop.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is …

Adds a Design and Product tool

---

README-zh.md

Fixed remove duplicate iStat pro

---

README.md

Related to issue #323 
If this is a relatively large or …

Added Rider to Developer Tools (IDEs)

---

README.md

This is for all the people that want to tailor their macOS experience.
- Added Gray to the list of System Related Tools

Add Gray to System Related Tools

---

README.md

NightOwl makes it easy to switch between macOS's Mojave's light and dark themes, which is out of the box a multi-step process to do. It's very convenient to switch theme depending if you're working at night or a bright coffee shop for example.

Adding NightOwl

---

README.md

Bitwarden is an open-source password management tool for MacOS, iOS and browsers. It also has a web interface.
Resolves #450 
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply …

Add Bitwarden

---

README-zh.md

tmux is NOT a `终端登录远程主机的命令行工具`
If this is a relatively …

fix tmux description

---

README-zh.md
README.md

V2rayU is proxy client based on v2ray.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you …

 add V2rayU

---

README.md

SCM Breeze is a set of shell scripts (for bash and zsh) that enhance your interaction with git. It integrates with your shell to give you numbered file shortcuts, a repository index with tab completion, and many other useful features.
I have been using this for awhile now in different development team and for our team is already a must-have set of scripts.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before …

Added SCM Breeze

---

README-zh.md

fix the url

---

README.md

Add spaceship-prompt

---

README.md

Dozer is in fact closed-source, after examining the repo. This is important since we cannot ensure whether the application will leak personal information.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're …

update icons for Dozer

---

README.md

Missing bang from introduction in #484

readme: Fix icon link for Buttercup

---

README.md

Treelo is an awesome app which let you create boards, lists, and cards and enable you to organize and prioritize your projects in a fun, flexible and rewarding way.
I did a little improvement in the Loremify description, that I pushed before, because of the redundancy.
-------------------------
Put an x in the boxes once …

Adds Trello.

---

README.md

Adding Clearview ebook reader, as in my opinion it's very convenient to read books and documents in separate tabs.

add Clearview

---

README-zh.md
README.md

Encrypto is a free encryption tool for encrypting files and folders, which is very useful. …

add encrypto

---

README.md

canSnippet is a powerful snippet management app for macOS. It allows users to easily save and access their precious pieces of code with simple keyboard shortcuts. The snippets can be included in any running application (IDE, text editor, terminal...).
Put an x in the boxes once you've completed …

Add canSnippet

---

README-zh.md

- 作图工具 类目
- ProcessOn
中文友好，上手快
- DrawIO
功能强大，支持多种导出格式
- OmniGraffle
端应用，稳定性更好
- Zoom
视频会议的同时可以屏幕共享，提供录制功能方便回看
- 马克飞象
多套配色，内容可同步至 印象笔记 账户
- BetterSnapTool
分屏工具，键盘和鼠标都可以快速完成分屏操作

Add Graph-making Tools And Some Other

---

README.md

Add Visual Paradigm to Developer Utilities

---

README-zh.md

https://github.com/jaywcjlove/awesome-mac/issues/530
Pull Request …

Add AppTrap

---

README-zh.md
README.md

Add Terminus

---

README.md

A powerful desktop app for creating responsive websites using the Bootstrap framework.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to …

Added Bootstrap Studio

---

README.md

Adding Windscribe to Proxy and VPN Tools (Closes #548)

---

README.md

Add Colorpicker

---

README.md

A lot of the time, people plug in their iPhones to their Mac to just charge their phones and do not necessarily want to open up iTunes. This fixes that by killing the iTunes process if triggered by plugging in your iPhone.

Added Overkill

---

README-zh.md
README.md

add AppIconBuilder

---

README.md

PPSSPP is a very powerful PSP emulator, with controller support for any controller (that can be connected to your device) and runs on anything, from MacOS/iOS to Blackberry.  …

added PPSSPP to list

---

README.md

I added LMMS, a free open-source DAW, and organized the Audio and Video Tools section. If i can find time ill organize any other cluttered sections.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here …

Organized Audio and Video tools, added LMMS

---

README.md

Discord has wonderful uptime, quality sound, amazing features, simplicity, customizable, seamless, gaming overlay, quick bug fixes, awesome PR, and more. ~ [@lovelessashi](https://twitter.com/lovelessashi/status/864953511850594304)
more review? [see on Twitter](https://twitter.com/discordapp/status/864916025229234176)
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to …

Add Discord

---

README.md

1. Works good with relatively big files, when Excel is not an option anymore. I tested it with a 560 MB CSV

Add TextQL

---

README.md

1. Added Streaker under the "Menu Bar Tools" heading
Closes …

Add Streaker

---

README.md

1. When Excel is not an option anymore because of the file size but you still want to have a GUI.

Add Tad - viewing and analyzing tabular data such as CSV files

---

README.md

Torimori Sweeper is an app I personally developed. It follows the Konmari method of cleaning by allowing you to go through your Downloads list, one file at a time, and choose whether to keep it in Documents, or put it in Trash. With this app, you can finally reach downloads-zero.
[link to app](https://coffeeboo.itch.io/sweeper)
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're …

Add Torimori Sweeper

---

README.md

1. Powerful tool that allows you to slice and dice your big data files as you want. And because it streams data there is no upfront wait time.

Add Miller

---

editor-plugin-zh.md
editor-plugin.md

Vscode plugin is useful to improve work efficiency for more people. Summarize some practical vscode plugin to prefect the list. Change as follows：
1. add more practical vscode plugin in list
2. provide english/chinese language comment
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your …

Perfect for vscode plugin list

---

README.md

1. Kind of command line Excel, works well with pretty big files

Add VisiData

---

README-zh.md

Modified the homepage address, the original address link to help center.
Add the download address is App Store.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you …

修改滴答清单官网链接、Mac APP

---

README.md

**Provide a link to the proposed addition.**
https://ticktick.com/about/mac
**Explain why it should be added**
TickTick is a great to-do app.
TickTick is a full-featured to-do list App, the best to-do list App I've used. And It crosses almost all platform, the Mac App is awesome.
It should be recommended to people who need an App to manage time. …

Add TickTick

---

README.md

Vivaldi is a secure and very customizable browser that is gaining popularity.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you …

Add Vivaldi

---

README-zh.md

提交RTX腾讯出品的内部通讯工具

---

README.md

Added the Sitesucker url. SiteSucker is a Macintosh application that automatically downloads websites from the Internet. This is a very helpful utility for developers.
- [ x] I have read the CONTRIBUTING guide
- [x ] I have explained why this PR is important
- [ x] I have added necessary documentation (if appropriate)

Added Site sucker to Dev Utilities

---

README.md

fixed Typo error and links in Site Sucker

Typo error in sitesucker

---

README.md

Added Safe In Cloud Password management

---

README.md

FastoRedis and FastoNoSQL

---

README-zh.md
README.md

Add Motrix to Download Management Tools

---

README-zh.md
README.md

Add Proxyman

---

README.md

- Added nnScreenshots visual timesheet software. 
- What makes this unique: This program takes a unique approach compared to other items on the list, and is more focused on a visual record with the tools to record what you were doing for each period of time, rather than attempting to _tell you_ if you were productive which we do not believe is genuinely possible.
- Disclosure: I am the developer of this software.

Added nnScreenshots timesheet software

---

README.md

Apple provides a set of system colors to Cocoa developers. This app would help developers to understand how they would look in dark and light mode.

Added MacSystemColors

---

README-zh.md
README.md

- [  ] Changing structure (organization) of list
If …

Add new advanced testing tools Katalon Studio because it is popular in United State

---

README.md

Adding SuperDuper! which is a great fully disk backup tool

Add SuperDuper!

---

README.md

'alacritty' is a great open source terminal emulator whose repo has over 15K stars. https://github.com/jwilm/alacritty …

Add 'alacritty' in 'Command Line Tools' section

---

README.md

**Issue**
#596 Marp links to outdated version
If this …

Fix outdated Marp link

---

README-zh.md
README.md

update for job

---

README.md

add flycut to clipboard manager list

---

README.md

TimeOut break reminders is great tool to manage your break during work on Mac. It is very easy to fall into bad habits when using a computer for hours on end. You care about what you are doing, so can sometimes push yourself too far, or over-strain yourself. The human body isn't built to sit in one position for endless hours, gripping a mouse or typing on the keyboard. Huge options to configure, free version with basic options (enough to use) make this tool one of the must have's. 
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're …

Add TimeOut - break reminders

---

README.md

[Touch Bar Simulator](https://github.com/sindresorhus/touch-bar-simulator) makes it possible to test Touch Bar integration in your app even if your computer doesn't physically have a Touch Bar (especially useful for Electron app dev as you then don't usually have Xcode installed). You can also use it as a virtual Touch Bar if you like how the Touch Bar works. …

Add Touch Bar Simulator

---

README.md

Chirper is a simple and tiny menu bar app for Buffer that helps you tweet your thoughts without opening anything. It's a very simple macOS app that can be helpful when watching a live stream or when you're at a conference and you need to quickly need to tweet something.
In my case (for example), I used it a lot during the FIFA World Cup, to tweet when France was scoring.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure …

Added Chirper

---

README.md

[Gifski](https://github.com/sindresorhus/gifski-app) is a very popular app for converting videos to GIFs. It has almost 5/5 rating in the App Store. [Users seem to love it.](https://github.com/sindresorhus/gifski-app/pull/71#issuecomment-480445987)
Disclaimer: I'm one of the maintainers.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are …

Add Gifski

---

README.md

[Caprine](https://github.com/sindresorhus/caprine) is the most popular third-party Facebook Messenger app. It's constantly updated and cross-platform.
I'm the maintainer of it.
(I also run the Awesome project. Nice list you got here!)
If this is …

Add Caprine

---

README.md

- Update keybase.io description to accurately reflect what the software does.
- Update keybase.io description to accurately reflect what the software does.

Update Keybase description.

---

README.md

Add Stremio app
1. Similar to pop-corn time, but better!

Add Stremio app

---

README.md

Fix Manta app link

---

README.md

HEIC is a new image format, so there are many places that don't support them. This app lets you quickly convert the images. It's a very popular app as lots of people don't know what to do about HEIC images.
If this is a relatively large or complex change, …

Add HEIC Converter

---

README.md

This CLI tool lets you easily toggle dark mode. It's a popular tool.

Add dark-mode

---

README.md

Taskbook is a great CLI  tool used by a lot of people. Link to repository: https://github.com/klaussinani/taskbook

Add taskbook

---

README.md

MS Edge Canary for Mac available for download. It should be in the list, since liked by many people, even though it's canary.
- [x ] I have read the CONTRIBUTING guide
- [x ] I have explained why this PR is important
- [x ] I have added necessary documentation (if appropriate) …

Add link to MS Edge Canary for Mac in Browsers

---

README.md

I've just added a note taking tool to the note taking section.
Fixes #547.

Add Notable in Reading and Writing Tools

---

README-zh.md
README.md

Although some of Katalon's software is opensource (such as Katalon recorder and some of their plugins), Katalon Studio is not opensource as can be seen [here](https://github.com/katalon-studio/katalon-studio), that repository doesn't have the source files, it is only used for issues (I assume).
I think we should hold the open source badge to a higher standard, and require the specific software listed to be open sourced, and not only some of its components.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before …

Removed Katalon Studio OSS badge as it is closed source

---

README.md

Not all applications show emoji picker at Touch Bar. This app allow use emoji picker at any application - browsers, IDEs, etc.
If this is a …

Add Touch Emoji

---

README.md

Adding Azure Data Studio tool to the list of tools under the Database category. This tool is free and cross-platform and installs well on MacOS. It is one of the few tools that connect to MSSQL Server that is free. It also has has some pretty nice features for a database tool which include intelliSense, code snippets, source control integration, and an integrated terminal.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to …

docs: add azure data studio tool under databases category

---

README.md

Please add Mingo.io app to this list. 
[Mingo](https://mingo.io/) is easy to use MongoDB GUI with mind-blowing features!

Add Mingo.io app

---

README.md

Free music application for MacOS. Search, play & download music for free.
Homepage: https://musicplus.io
Email: contact@musicplus.io
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is …

add MusicPlus application

---

README-zh.md

Reeder 4 is release.
If this is a relatively large or …

Update Reeder 4 for Mac

---

README.md

Update Reeder 4 for Mac.

---

README-zh.md
README.md

add tmuxinator

---

README-zh.md
README.md

Add QSpace

---

README.md

'kitty' is a cross-platform, fast, feature full, GPU based terminal emulator.
https://github.com/kovidgoyal/kitty
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution …

Added 'kitty' in 'Command Line Tools' section

---

README.md

I've added Bidbar, an app that allows you to manage bash commands from the menu bar and run/copy them using auto-generated keyboard shortcuts. https://www.getbidbar.com
If this is a relatively large or complex change, kick off the …

Add Bidbar

---

README.md

FSNotes is a worthy addition to the Note-taking section. A fast, native note app on macOS and iOS in a world of poorly performing Electron apps.

Add FSNotes to Note-taking section

---

README.md

I've added Nib Unlocker,  an app that attempts to parse a compiled nib file(ios/UIKit based nib's only) and output a xib file that Interface Builder or Xcode can edit and use as .xib in your project. …

added Nib Unlocker

---

README.md

Removed Encrypto, as it's closed source and unauditable. It's inherently
dangerous to use closed-source encryption tools and we shouldn't be
recommending it to users.

Added Encryption section w/ macOS Quick Lock

---

README.md

Update RSS list

---

README.md

nushell is modern shell with unique philosophy. 
It is pipe based and it is well implemented with Rust.
I think it should be on the list. Just take a look if not have seen yet.
https://github.com/nushell/nushell …

Add nushell

---

README.md

I added both neo4j (graph database to the databases section) and HazeOver (productivity utility) to the productivity section. Both additions are good tools that I think deserve to be part of this great list.

Add HazeOver and neo4j

---

README.md
editor-plugin.md

Added Magic Wormhole as a command line tool  because I have personally found it to be useful. It also helps to side-step an intermediate step (uploading files to some cloud provider, who can basically read all your content).
Added TabNine to Editor plugins because it's relatively new, helpful, and based on deep learning tech.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're …

Added Items.

---

README.md

I tried Paste last week, they have a trial period but no free working version.

Remove freeware icon from Paste

---

README.md

The only free (for now) working Kafka desktop UI I was able to find. Makes a developer life much better :)

Add Conduktor - Kafka desktop client

---

README.md

Was updated Appstore link to Microsoft Office in README.md
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your …

Updated Appstore link to Microsoft Office

---

README.md

Added PushMate tool to the list under Developer Utilities.

Added PushMate to the Developer Utilities section

---

README-zh.md
README.md

Pencil2D moved to "Design Tools" category from "Screencapturing software"

Pencil2D moved to "Design Tools" category.

---

README.md

Add MakeHuman

---

README.md

Added Background Music to the System Related Tools.

Added Background Music to System Related Tools.

---

README.md

**What types of changes does your PR introduce?** 
Adding the excellent Day One app + new "Journaling" section

Add Journaling section/app

---

README.md

Add yabai tiling window manager which is a rewrite of chunkwm. It is now in active development whereas chunkwm is not. It also integrates much better with macOS and provides a better experience for the user.

Add yabai tiling window manager

---

README.md

Added Journey as diary option

---

README.md

1. bindPDF (https://github.com/vishaltelangre/bindPDF) - Quickly combine multiple PDF documents into a single PDF document.
2. Kyapchar (https://github.com/vishaltelangre/Kyapchar) - Simple screen and microphone audio recorder for Mac.
N/A

Add "bindPDF" and "Kyapchar" macOS apps

---

README.md

I'm not sure if this app qualifies as freeware. The app itself is free and fully functional, but it offers a commercial icon collection (optional).
I just started using this app myself, and it deserves a recommendation. The other icon managers on this list either require a license/subscription, or lack many features that this app offers.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any …

Add Nucleo app

---

README-zh.md
README.md

https://github.com/semaja2/InsomniaX
Page is not found, project not supported and closed 4 years ago.

Remove unactual InsomniaX link from list 

---

README.md

1.  I thought it could be very useful for people here, not necessarily for IoT geeks but also devs or just productive hackers. For instance, Lazy allows me to deploy a side project I have through Netlify with one easy shortcut. I think you will find that Lazy adapts very nicely to some of your workflows. Curious to see what others uses people come up with!
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, …

Add Lazy-App to productivity

---

README.md

Change the Slack listing from the just the slack.com page to the actual Mac landing page.

Change Slack link to Mac page

---

contributing.md

Update CoC link in Contributing

---

README.md

Deluge is a free, lightweight and open source BitTorrent client.
Deluge is a lightweight, Free Software, cross-platform BitTorrent client. I've been using it on my Mac for years.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to …

Added Deluge to Download Management Tools

---

README.md

Add DaVinci Resolve

---

README-zh.md
README.md

Hungrymark is very useful for collection bookmarks of your focus things like files, folders, and webs.  and you can fast access these bookmarks
If this is a relatively large or complex change, kick off the discussion by explaining …

Add Hungrymark

---

README-zh.md
README.md

1440 Minutes Left Today is a small and very simple menu bar app. It shows you how many minutes you have left until the day is over. There are plenty of groups which can benefit from it:
- Procrastinators can use it as a little motivator to use their time wisely.
- Night owls can use it as a reminder to go to bed at a reasonable hour.
- Photographers and other creatives doing 365/30/... days projects can use it to produce something every day before midnight.
Put an x in the boxes once you've …

Add "1440 Minutes Left Today" to Productivity

---

README.md

A free, beautiful menubar app for managing local websites. It helps you serve up static sites and Rack apps with simple URLs and zero configuration. More about it here: https://anvilformac.com/

Added Anvil

---

README-zh.md
README.md

新增了一款图床客户端 uPic，macOS原生应用程序，运行丝般顺滑，功能强大且简洁。
If this is …

add:新增图床应用uPic

---

README-zh.md
README.md

修复问题如下
iPic应用在英文自述文件中存在两个的问题
PicGo应用只存在于中文自述文件的问题
If …

fix: The iPic app is recurring and the PicGo app only exists in the Chinese directory.

---

README.md

Not really a bug, but an update to the existing description.
Spectacle is no longer actively maintained ([as stated on the website](https://www.spectacleapp.com/)) and this PR is adding this information to the `README`. Author of Spectacle is [recommending](https://github.com/eczarny/spectacle#important-note) the …

Spectacle: add deprecation warning

---

README-zh.md
README.md

- Add HapticKey to English and Chinese version
- Remove trailing space 
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you …

Add HapticKey to English and Chinese version

---

README-zh.md
README.md

A simple fix of a wrong VM**W**are to the right VM**w**are
The fix isn't so important. At the same time, it's better to don't have typos than have typos in the Project.
Thank you.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, …

Fix a typo in 'VMware'

---

README-zh.md

增加一款程序员效率工具，没有之一的工具，发现居然没人添加

---

README-zh.md

推荐iShot，一款完全免费，功能强大的截图贴图工具，支持截图和贴图，滚动截图等功能。
修复了mongoDB.app的GitHub Repositories链接丢失的问题。
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to …

推荐截图工具iShot，修正一处错误

---

README-zh.md

腾讯柠檬清理是腾讯推出的一款免费的Mac清理软件，用于替代原来 Mac电脑管家；
腾讯柠檬精选是腾讯Lemon团队推出的一个Mac软件分享平台，用于收录免费、正版、好用的Mac产品。
腾讯电脑管家-“电脑管家 for Mac 带应用市场” 链接跳转到腾讯柠檬清理页面，不是Mac应用市场。
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to …

推荐腾讯柠檬清理和腾讯柠檬精选，修复一处错误

---

README.md

1. Added hidden to Menu Bar Tools. I'm a long time Bartender user and I think hidden is a great alternative.

added hidden to Menu Bar Tools

---

README.md

Replace dead link for Torimori with a cached link

---

README.md

Add Loca Studio to Developer Tools - Developer Utilities.
It's an awesome macOS app for analyzing, reviewing, and editing app translations. See https://www.cunningo.com/locastudio/index.html more more information.
If this is a …

Add Loca Studio to Developer Utilities

---

README.md

add CleanShot to Screencapturing Software. It's a good and beautiful piece of software to capture or make a GIF. 
Closes #716 …

add CleanShot to Screencapturing Software

---

README.md

Remove deprecated upterm command line tool

---

README.md

Added Mouseless to Utilities. It's a good and beautiful piece of software to get the keystrokes ingrained in your muscle memory for good.
If this is a relatively large or complex change, kick off the discussion by explaining why …

Added Mouseless app to Utilities

---

README.md

I have been personally using all these apps and i'm happy with those.
1. Sensei - The blazing fast Clean feature in Sensei will help you find and delete unnecessary files that are taking up your storage space, freeing up gigabytes of storage without touching your personal files.
2. Gooba - With Gooba you no longer need separate apps to write your notes and manage your tasks. You have everything here, with a simple and interactive design.
3. One Switch - All your powerful switches in one place to …

Added Sensei, Gooba, One Switch, Stack and Shift

---

README.md

Iconset is a free SVG icon organizer working on both Windows and Mac, and it supports cloud syncing. This is the only one app which has these features and should help designers a lot. Some designers from great companies like Google, Apple or Amazon etc. are using it.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going …

feat: Added Iconset

---

README.md

Added new app under the "Collaboration and Team Tools".
[Krisp](https://krisp.ai) - An AI-powered noise canceling app that mutes background noise during calls.
If this is a relatively large or complex change, kick off the …

Add Krisp - An AI-Powered noise canceling app.

---

README-zh.md
README.md

Dnote is a command line note-taking application that can be easily installed on macOS via Homebrew. It is a free and open source software. It helps users capture and retrieve new information easily. I have been maintaining and using it on macOS for around 3 years, and along with other users, am quite happy with it.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to …

Add Dnote to the Note-taking section

---

README-zh.md

Added an app under the "RSS".
[irreader](http://irreader.fatecore.com) - A free, versatile, and open source RSS reader that supports subscriptions to podcasts and any websites. …

Add irreader to RSS

---

README.md

Dato replaces the system menu bar clock with something much more useful. It gives you a calendar, calendar events, and time zones. It's a popular app that people seem to love.
It currently has 5/5 stars in the US App Store: https://apps.apple.com/us/app/dato/id1470584107?mt=12
Disclaimer: I'm the author.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. …

Add Dato to Menu Bar Tools section

---

README.md

1. Even though macOS has Directory Utility built-in, this tool is cross-platform and much more powerful 

Add Apache Directory Studio

---

README.md

1. English iHosts link has changed

Fix iHosts English link

---

README.md

I just added an App Store badge into the Todoist's entry, since it can be downloaded from there.
Just a simple PR.

Adds the Mac App Store badge into the Todoist's entry

---

README.md

This PR removes Wunderlist from the list, since it's gonna be shut down (next May 6): https://www.wunderlist.com/switch) by its founder (who now work for Microsoft's ToDo app). ToDo is already listed in this README, so I'm just removing.
The main reason for this removal is security. It's not safe to install abandoned apps.
- [] I have added necessary documentation (if appropriate)
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives …

Removes Wunderlist from the list

---

README.md

You have incorrect information for iTranslate – it doesn't translate in Safari. At least its Mac app. I added Mate that actually translates in Safari and is 10x better integrated with macOS.
You have incorrect information for iTranslate – it doesn't translate in Safari. At least its Mac app. I added Mate that actually translates in Safari and is 10x better integrated with macOS.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're …

Mate added to translation tools

---

README.md

I copied a line and didn't change the link name in the previous update, when adding Mate to translation tools. Fixed now.
I copied an existed line to add a new product, but forgot to change the name. Fixed.
If this is a relatively …

Ludwig -> Mate app name

---

README.md

Plash is a useful that that lets you put any website as you desktop background. It's free and open source.
https://github.com/sindresorhus/Plash

Add Plash to General Tools

---

README.md

Added Tomato 2 - a very nice and simple Pomodoro timer.

Added Tomato 2

---

README.md

1. Adds the free open source profiling instrument called Timelane
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, …

Adding Timelane profiling instrument

---

README.md

SoftMaker Office is relatively new to macOS, but it might be interesting to some, so I added it to the list.
n/a

Added SoftMaker Office

---

README.md

Added useful pomodoro application

Add pomodoro cycle app

---

README.md

ExifCleaner is a freeware, opensource GUI app for removing exifdata from images and videos with a simple drag and drop. There are multiple Mac users who use it on a daily basis without issue. It's been out for a while now and the main bugs are ironed out. Disclaimer: I'm the author.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of …

Add ExifCleaner to Other Tools section

---

README.md

Added Dropbox to the list because I used it for some years for screenshotting, it worked great and it wasn't already added in here.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. …

Added Dropbox to the list of screenshot softwares

---

README.md

1. Brave Browser is open-sourced, so a link to its GitHub organization is added

Mark Brave as open-source software

---

README.md

Update name of encryption app to deadbolt

---

README-zh.md

添加 MAC萌新网 进黑名单

---

README.md

Removed the chunkwm link as it is dead by now and was replaced by yabai which is already linked to slightly below.

Removed chunkwm

---

README.md

Ultra TabSaver it's a very useful extension for safari, and it's open source so it's free for everyone.
Main features:
- Save all open tabs in a tab group
- Open all the tabs in a tab Group
- Copy all the websites in a TabGroup and paste it anywhere
- Edit the name of the Tab Group

Add ultra tab saver

---

README.md

I'm adding a tool I wrote that I think increases productivity for people using the terminal. Instead of forgetting an idea you can now just input it into a list and `eureka` pushes it to your git repository.

Add eureka CLI productivity tool

---

README.md

Because it is a recent application, I used it and it's a good tool to version controller git based
If this is a relatively large or complex change, kick off the discussion by explaining why …

Add Gitfox

---

README.md

Rectangle is a window management app based on Spectacle, written in Swift. this can replacing Spectacle which is no longer maintained.
If this is a relatively large or complex change, kick off the discussion by explaining why you …

Added Rectangle

---

README.md

Close #799
Add another window switcher AltTab to the list. Because AltTab is currently being maintained and is a good open source alternative.

Add AltTab to the window management section

---

README.md

Added an app under the "Menu Bar Tools".
MeetingBar - A free, versatile, and open-source menu bar app for showing the next meeting from the calendar.

Add MeetingBar to Menu Bar Tools

---

README.md

Add Feedy application to RSS section

---

README.md

Edison Mail is a simple, easy-to-learn and beautiful email client.
If this is a relatively large or complex change, kick off the discussion by …

Added Edison Mail as an email client.

---

README.md

xonsh shell creates unique experience of combination Python with shell commands and pipes. The sane language allows to use the shell for wide spread of tasks easily.

xonsh shell is a Python-powered, Unix-gazing shell language and command prompt

---

README.md

xxh brings your favorite shell (fish, xonsh, zsh, osquery) wherever you go through the SSH. It works like magic. Demo:
* zsh - https://asciinema.org/a/rCiT9hXQ5IdwqOwg6rifyFZzb
* xonsh - https://asciinema.org/a/osSEzqnmH9pMYEZibNe2K7ZL7

xxh - Bring your favorite shell wherever you go through the SSH.

---

README.md

The app makes it super easy to just record some audio.
https://sindresorhus.com/recordia

Add Recordia

---

README.md

The app makes the system share menu much more useful.
https://sindresorhus.com/shareful

Add Shareful

---

README.md

Now contains a url that links to more quicklook plugins.

Update the QuickLook Plugins section

---

README.md

I added Obsidian the note-taking app to the list.
If …

Added Obsidian to list

---

README.md

Hey @jaywcjlove 
just fixing a link.
Cheers!
Broken link fixed

Fixing broken link for MySQL Chrome

---

README-zh.md

hack-store don't work anymore.

Remove hack-store

---

README.md

1. Good looking tool, free, open-source, actively maintained 

Add Beekeeper Studio to Databases

---

README.md

Hey @jaywcjlove 
just fixing a link.
Cheers!
If this is …

Fixing tool link

---

README.md

Adding an entry for a new file manager called Fileside.

Add Fileside

---

README-zh.md
README.md

It's a decent app to hide Dock automatically.

Add IntelliDock

---

README-zh.md

add 360 Browser

---

README-zh.md
README.md

It's a good app for Redis and it's free.
If this is a …

add Another Redis Desktop Manager

---

README.md

So Mac users considering buying a new Apple SIlicon or Apple M1 Mac can test specific apps from their current mac to confirm compatibility.

Add Apple Silicon App Test, for #873

---

README.md

There are two Preset Brewery entries

Remove duplicate of Preset Brewery

---

README.md

xcodes is a command-line app that makes Xcode installation and management a lot easier for developers that need more control than simply installing the latest version from the Mac App Store, especially in automation use cases.
Note that this is a different program than Xcodes.app (a GUI app) proposed to be added in #871.
Put an x in the boxes once you've completed each step. You can also fill these out after …

Add xcodes

---

README.md

- Add Microsoft Remote Deskto‪p as freeware
1. I use it in my Daily Work, is stable, secure, useful and free.

Update Remote Login Software section

---

README.md

Added my open source app, linked. It's a journal/diary app.

✨ add linked

---

README.md

The original link of tomato 2 (https://www.notion.so/967a0a6484c64162a026d1f48cad18dc) directs to a notion site which is not open for users. Instead, the official site of tomato 2 is https://tomato2.app . 
NA

Update website link to tomato 2

---

README-zh.md
README.md

See #885 for more details.
If this is a relatively …

Remove OpenOffice

---

README.md

Add Omniplayer for mac video player tool.

---

README-zh.md
README.md

Docker's open source url is pointed to GitHub CLI's repo. I changed it to Docker's organization.

Fix Docker's open source url

---

README.md

Add Royal TSX to Remote Login Software

---

README.md

It's useful to be able to see the UTC time in menu bar if you do any kind of development where you deal with UTC time, like servers, logs, etc.
https://sindresorhus.com/utc-time

Add UTC Time

---

README-zh.md
README.md

Add Translatium app to the list. 
Translatium is one of the most popular translation apps on macOS (#10 Travel app on Mac App Store). The app is free and open source. Learn more at https://translatium.app
I didn't add the Freeware icon because the app will introduce an optional premium package soon.

Add Translatium app

---

README.md

I've changed the entry for iFFmpeg to ffWorks, as iFFmpeg has been renamed. 
The provided link ([http://www.iffmpeg.com/](http://www.iffmpeg.com/)) was also broken, so I have changed it to the new domain. ([https://www.ffworks.net/](https://www.ffworks.net/))

Fix iFFmpeg entry

---

README.md

- Add Eagle App to the list of File Organization Tools
- Eagle App is a simple and intuitive file manager with tag and annotation. It helps you easy to get your hands on file organization and it improves productivity. …

Add Eagle App to File Organization Tools

---

README-zh.md

change Eagle app from 其它实用工具 category finder list to 设计和产品 category 其它工具 list as its more suitable
- change Eagle app from 其它实用工具 category finder list to 设计和产品 category 其它工具 list as its more suitable
- the supported files in Eagle App such as PNG, JPG, GIF, PSD, AI, PDF, EPS, TIFF, MP4, MOV, M4V, OBJ...etc tend to fall under the design category more  …

change category and listing area

---

README.md

change from utilities category to design and product category
- change from utilities category to design and product category as its more suitable.
- support all major font, source, image, RAW, video, 3D, audio, and office files such as PNG, JPG, GIF, PSD, AI, PDF, EPS, TIFF, MP4, MOV, M4V… etc. which tend to be more suitable under design category.  …

change from utilities category to design and product category

---

README.md

Updated URL PopCorn site (line 647)
No break on code

Updated URL PopCorn site (line 647)

---

README.md

BlackHole should be added because there is no freemium audio driver app in the awesome list yet.

Add BlackHole

---

README-zh.md

I'm adding 8 items to the list:
1. Notion: a new style note/article manager, support many rich text types. 
2. Resilio Sync: personal cloud software, works in p2p way like bittorrent, powerful and easy to use.
3. Syncthing: opensource alternative of `Resilio Sync`, free and stable.
4. GPG Suite: one simple package with …

Add 8 useful software in my daily life

---

README.md

- Removed _MacAssistant_ because its author did not update their application for 2 years now.
- Added _Google Assistant (Unofficial Desktop Client)_ as a replacement for _MacAssistant_ since it is actively maintained and also useful and has a beautiful UI.
If this is a relatively large or complex change, kick off the discussion by explaining …

Replace MacAssistant with A New Google Assistant Application

---

README-zh.md
README.md

Add redis-pro

---

README-zh.md

Add 360 Compression

---

README-zh.md

#946
This is the link to the US app store because it is not available in the Chinese app store
https://apps.apple.com/us/app/microsoft-remote-desktop/id1295203466?mt=12
This is the download address, available in China.
https://go.microsoft.com/fwlink/?linkid=868963
Official document on how to use it.
https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-mac
Put an x in the boxes once you've completed each step. You can also fill these out after …

Add Microsoft Remote Desktop

---

README-zh.md
README.md

增加2款音频制作软件

---

README-zh.md

Add aliyundrive

---

README-zh.md

upgrade new link: https://folivora.ai/
The original link is invalid, it is an old version of the software. Replace with a new link.

Fix BetterTouchTool

---

README.md

I propose adding `QEMU` which is generic and open source machine & userspace emulator and virtualizer available for MAC to the virtualization category. 
Many people are using its emulation abilities for doing different things like to build multi arch docker images, etc. It should be in this list for sake of completion. 
Put an x in the boxes once you've completed each step. You can also fill these out after …

Add QEMU to Virtualization 

---

README.md

Link - https://presentify.compzets.com/
App Store - https://apps.apple.com/app/id1507246666
Setapp - https://go.setapp.com/stp285?refAppID=401&utm_content=button&utm_medium=vendor_program
**Why this should be added or why is it important?**
Given that we are all working from home and spending most of our time on video calls, this little tool may prove to be quite useful in articulating your thoughts while presenting, teaching, etc. With this app, you can draw anywhere on your screen, highlight your cursor, draw on a whiteboard, and so much more.
**Describe each of your changes here to communicate to the …

Add Presentify Mac App

---

README.md

I think SwiftBar should be added because its a great alternative to xbar and BitBar. Moreover, SwiftBar's plugin API is adopted from the BitBar, which means that SwiftBar can run any existing BitBar and xbar plugins.
If this is a …

Add SwiftBar

---

README-zh.md
README.md

1. Terminus was renamed to tabby though https://github.com/jaywcjlove/awesome-mac/pull/948 this pull request addressed this for English README there was a typo in the name.
2. Rename from Terminus to Tabby in the Chinese README too. 
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your …

Fix Tabby (formerly Terminus)

---

README.md

Adding info about `SwiftPlantUML`, a really cool Xcode extension to generate class diagram(s) for Swift code

Add SwiftPlantUML to Developer Utilities

---

README.md

Open-source clipboard with good UI
Yippy is an open-source, free clipboard manager with many features to be added. Yippy currently also has features that may satisfy the normal user (e.g. shortcuts for the last 10 copied items). It also has a user-friendly UI, all activated with cmd + shift + V. 
Put an x in the boxes once …

Added Yippy

---

README-zh.md
README.md

Add a free and efficient decompression tool.
N/A

Add Unarchive One Free zip tool

---

README-zh.md
README.md

1. Just change the link address.
- Thanks
- N/A

Yunxijun patch 1

---

README-zh.md
README.md

1. Added some useful software recommended by many people
- Thanks to share it.
- N/A

Update some useful tool 

---

README-zh.md
README.md

From [the project README](https://github.com/aonez/Keka#legacy-info):
> Keka started in [SourceForge](http://sourceforge.net/projects/keka) as an open source project. Since 1.0 is a closed code project ([one of the reasons](http://web.archive.org/web/20180615184129/http://trac.keka.io/ticket/14)) and there're no plans to open the code again.
Don't get me wrong, I love Keka, and it will probably remain free forever, but the fact it is no longer open source is also true. The labels should reflect …

Remove open source label from Keka

---

README-zh.md
README.md

Betterzip is no longer a Freeware but a Shareware now.

Remore Freeware label from BetterZip

---

README.md

1. Adding Jetbrains DataSpell IDE for Data Scientists to the list
Not Applicable

Added Jetbrains DataSpell

---

README-zh.md
README.md

Added the newly launched [rcmd](https://lowtechguys.com/rcmd/) app to the **Window Management** list.

Add rcmd app switcher

---

README-zh.md

Raycast
If this is a relatively large or complex …

add Raycast app

---

README.md

1. If you're adding something to the list, be sure to explain why it should be added:
This program is awesome
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you …

add Mp3tag

---

README.md

1. If you're adding something to the list, be sure to explain why it should be added:
best offline password manager. awesome …

add Strongbox password manager

---

README.md

CursorSense is a prefPane item that lets you tweak the mouse acceleration curve. Specifically, it allows you to turn off mouse acceleration at all, which is helpful for gamers.

Add CursorSense

---

README.md

new:
```
https://github.com/overtake/TelegramSwift
https://itunes.apple.com/us/app/telegram/id747648890?mt=12
```
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder …

add Telegram Github + AppStore info

---

README.md

Small app that tracks working hours, is private, and stores data in local CSV file.
Adding a new app

Add Work Hours app

---

README.md

It's a common need to want to know your internet speed, and this app does it in a very simple way. It also comes with powerful features like Shortcuts support and history. Most other tools for this are biased (for example, Speedtest by Ookla). Speediness returns more realistic result by running the tests in parallel. [More here](https://sindresorhus.com/speediness#faq) …

Add Speediness

---

README.md

**What types of changes does your PR introduce?** 
Add an open source MenuBar app to remind you to turn on your Firewall, FileVault, Screen Lock, etc. 
None.

Add Pareto Security app to Security category

---

README-zh.md
README.md

The super productivity is really a great open source todo list with:
1. Use timeboxing and track your time.
2. Integrate with Jira, GitHub, GitLab and OpenProject.
3. Attach context information to tasks and projects.
If this is a …

Add super productivity

---

README.md

Add an open source Vulnerability Management tool that helps to keep OS and Apps updated.
None.

add Mana Security app to Security Tools

---

README-zh.md

Update Design Tools
If this is a relatively large or …

Update Design Tools

---

README.md

- [*] New addition to list
BlurScreen helps blur sensitive data instantly anywhere on-screen, while recording or screen sharing. No post-editing is required.
It is launched on 1 Jan and already getting some great responses [reviews](https://www.trustpilot.com/review/blurscreen.app)
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of …

Add BlurScreen App

---

README.md

Shottr is an amazing Screen Capturing application that provides crucial features like Markup, OCR, Scrolling capture etc. and the best part is that it is a freeware. I have been using the application for many months now and have found it to be very useful, so felt that it should be included in this list for others to benefit as well.

Add Shottr under Screencapturing Software

---

README.md

Adds ripgrep the more popular (according to GitHub stars) and faster alternative to `the silver searcher`. Tool for searching text/code patterns on the command line.

Add ripgrep to Command Line Tools

---

README-zh.md
README.md

Add [Fig](https://fig.io) to the Command Line Tools list. It is a tool for command line auto completion, supports custom implementations.

Add Fig to Command Line Tools

---

README.md

[One Thing](https://sindresorhus.com/one-thing) lets you put the most important task or goal in the menu bar, so it's always there, and there's less chance for you to forget. A lot of users has said it has really helped them focus on their current task. The app is also fully scriptable.

Add One Thing

---

README.md

NOTE: There is a [similar PR](https://github.com/jaywcjlove/awesome-mac/pull/887) but it is old and is not passing in the pipe. I think that we may merge this PR and close the old one.
[Flameshot](https://github.com/flameshot-org/flameshot) is one of the most popular screenshot open source application  …

add flameshot

---

README.md

1. Fork is now a paid application: https://github.com/fork-dev/TrackerWin/issues/571

Fork is no longer free

---

README-zh.md
README.md

Add Fishing Funds

---

README.md

____
fish is not a terminal , it's a shell. It was listed as a terminal.

correct what fish is. Fish is a shell *NOT* a terminal

---

README.md

BetterMouse is a new utility that has all features external mice need to function better and more efficiently. It has smooth scroll, cursor acceleration & speed tweak, and button/gesture remapping to various actions and shortcuts all in one, like no other similar tools can do currently. …

Add BetterMouse

---

README-zh.md
README.md

Li-ion and polymer batteries (like the one in your MacBook) last the longest when operated between 20% and 60%. Keeping your battery at 100% most of the time will significantly shorten the lifespan of your MacBooks battery and Replacing an old battery is not only harmful to the environment but also costs up to $ 199. With AlDente installed, you can set a charging limit in a more healthy charging range, and with more features like Sailing Mode or Heat Protection, you can keep your battery healthy even longer.
Put an x in the boxes once you've completed each step. You can also fill these out after …

Add AlDente

---

README-zh.md
README.md

MenubarX is a powerful Mac menu bar browser that can pin any webpage on your menu bar just like an App.
Whether it's a frequently visited website page or a website lacking native App, MenubarX can help users use it more efficiently and conveniently!
Take a quick look
#2 Product of the Week in [Product Hunt](https://www.producthunt.com/posts/menubarx) when I created this PR.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are …

Add MenubarX

---

README.md

Craft is an awesome notetaking/writing tool. It deserves its place among all those note takers listed in this awesome list. …

Add Craft Docs to the list.

---

README.md

I missed the link to Craft docs app store. Added it to the app store icon.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before …

Correct craft link

---

README.md

(Hope I am doing this right, I am new to both GitHub and contributing to repos)
Added Workspaces app to the productivity section. Checked the links this time.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. …

Add workspaces app

---

README.md

I think Bear is more of a note taking tool than a text editor. The description of the app on the app site states that _"Bear is a beautiful, flexible writing app for crafting notes and prose."_ That is why it should be moved to the note-taking section.
Put an x in the boxes once you've completed each step. You can also fill …

Move bear to Note-taking section

---

README-zh.md

增加Maccy剪贴板管理工具软件

---

README-zh.md
README.md

update reeder version

---

README-zh.md
README.md

fix: repo url

---

README.md

Added Wavebox to the Communication & Team tools section
Adding the Wavebox app, that has had a mac client since 2016 …

Add Wavebox

---

README-zh.md

1. Fire 输入法是一个开源的，轻量，功能强大的五笔输入法

添加Fire五笔输入法

---

README-zh.md

fix: 修复链接错误的问题

---

README-zh.md

Add apifox

---

editor-plugin-zh.md

Signed-off-by: WangYongsi <codedog999@163.com>
1. Remove VS Code plugin - `Debugger for Chrome`
2. Add spaces between Chinese and English
3. Modify typos

Modify the text format

---

README.md

Since the IDE from Jetbrains was added, don't leave PHPStorm :)
Since the IDE from Jetbrains was added, don't leave PHPStorm :)

Add PHPStorm

---

README-zh.md
README.md
editor-plugin.md

Atom will be archived and sunset: https://github.blog/2022-06-08-sunsetting-atom/

Remove Atom and its plugins 

---

README.md

[Time Machine Inspector](https://github.com/probablykasper/time-machine-inspector) lets you look at what files changed in each incremental backup, which lets you see what might be taking up space. It helps me get some insight and figure out what to exclude from Time Machine backups.
If this is a relatively large or complex change, kick off …

Add Time Machine Inspector

---

README.md

Adding `XCSnippetsApp`, a free and open-source macOS application to explore code snippets from the Swift and iOS community, view and edit the snippets before adding them conveniently to Xcode.

add XCSnippetsApp

---

README.md

add deep and lingvanex translation tools

add DeepL, Lingvanex and Terminus

---

README.md

Ubuntu VMs on demand for any workstation
Get an instant Ubuntu VM with a single command. Multipass can launch and run virtual machines and configure them with cloud-init like a public cloud
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you …

Add Multipass

---

README-zh.md

Paste is not free

---

README-zh.md

There are items that belong to clipboard manager category but are classified into other categories.

Clean up and update clipboard manager category

---

.github/workflows/ci.yml
README-zh.md
README.md
editor-plugin-zh.md
editor-plugin.md

1. Add a dash between title name and description.
2. Capitalize h in GitHub.
3. Capitalize the first letter in the description.
4. Add linespaces before and after heading.
Update for increasing the readability.

README Formatting

---

README.md

This PR added massCode app to the list. 
**Organization**
massCode allows you to organize snippets using multi-level folders as well as tags. Each snippet has fragments - tabs, which gives even greater level of organization.
**Editor**
A snippet manager must not only provide organization of snippets but also have a good code editor. That's why under the hood of massCode there's Ace. Ace is a high performance code editor which supports syntax highlighting for over 170 languages. We also added a Prettier to code formatter.
**Markdown**
massCode allows you to write in Markdown and provide support to syntax …

Add massCode

---

README.md

Added Obsidian to Markdown Tools section.
Added Obsidian end of the [markdown tools list](https://github.com/jaywcjlove/awesome-mac#markdown-tools).
Obsidian is a great markdown tool which I have been using for months now. It has so much cool features that is why it should be on that list.
There is no further comments.

Add Obsidian to Markdown Tools Section

---

README.md

> OnlyOffice - https://www.onlyoffice.com
ONLYOFFICE Desktop Editors is a free office suite that combines text, spreadsheet and presentation editors allowing to create, view and edit documents stored on your Windows/Linux PC or Mac without an Internet connection. It is fully compatible with Office Open XML formats: .docx, .xlsx, .pptx.

Add OnlyOffice

---

README.md

> MusicBrainz Picard - https://picard.musicbrainz.org/
MusicBrainz Picard is a cross-platform (Linux, macOS, Windows) audio tagging application. It is the official MusicBrainz tagger. Picard supports the majority of audio file formats, is capable of using audio fingerprints AcoustIDs, performing CD lookups and disc ID submissions, and it has excellent Unicode support. Additionally, there are several plugins available that extend Picard's features.

Add MusicBrainz Picard

---

README.md

> Added Logseq - https://logseq.com/
Logseq is a privacy-first, open-source knowledge base that works on top of local plain-text Markdown and Org-mode files. Use it to write, organize and share your thoughts, keep your to-do list, and build your own digital garden.

Add Logseq

---

README.md

> FreeTube - https://freetubeapp.io/
FreeTube is a YouTube client for Windows, Mac, and Linux built around using YouTube more privately. You can enjoy your favorite content and creators without your habits being tracked. All of your user data is stored locally and never sent or published to the internet. FreeTube grabs data by scraping the information it needs (with either local methods or by optionally utilizing the Invidious API). With many features similar to YouTube, FreeTube has become one of the best methods to watch YouTube privately on desktop.

Add FreeTube

---

README.md

> LibreWolf - https://librewolf.net
This project is an independent fork of Firefox, with the primary goals of privacy, security, and user freedom.
LibreWolf is designed to increase protection against tracking and fingerprinting techniques, while also including a few security improvements. This is achieved through our privacy and security-oriented settings and patches. LibreWolf also aims to remove all the telemetry, data collection, and annoyances, as well as disabling anti-freedom features like DRM.

Add LibreWolf

---

README.md

> ElectronMail - https://github.com/vladimiry/ElectronMail
ElectronMail is an Electron-based unofficial desktop client for ProtonMail. The app aims to provide enhanced desktop user experience enabling features that are not supported by the official in-browser web clients. It is written in TypeScript and uses Angular.

Add ElectronMail

---

README.md

> Mailspring - https://getmailspring.com
Mailspring is a new version of Nylas Mail maintained by one of the original authors. It's faster, leaner, and shipping today! It replaces the JavaScript sync code in Nylas Mail with a new C++ sync engine based on [Mailcore2](https://github.com/MailCore/mailcore2). It uses roughly half the RAM and CPU of Nylas Mail and idles with almost zero "CPU Wakes", which translates to great battery life. It also has an entirely revamped composer and other great new features.
Mailspring comes packed with powerful features like Unified Inbox, Snooze, Send Later, Mail Rules, Templates and more. Mailspring Pro, which you can unlock with a monthly subscription, adds even more features for people who send a ton of email: link tracking, read receipts, mailbox …

Add Mailspring

---

README.md

> Etcher - https://www.balena.io/etcher/
Etcher is a powerful OS image flasher built with web technologies to ensure flashing an SDCard or USB drive is a pleasant and safe experience. It protects you from accidentally writing to your hard drives, ensures every byte of data was written correctly, and much more. It can also directly flash Raspberry Pi devices that support USB device boot mode.

Add Etcher

---

README.md

> Zettlr - https://www.zettlr.com/
A modern markdown editor streamlined for professionals. It supports citations and Zettelkasten knowledge management.

Add Zettlr

---

README.md

> Tutanota - https://tutanota.com
Tutanota is an email service with a strong focus on security and privacy that lets you encrypt emails, contacts, and calendar entries on all your devices.

Add Tutanota

---

README.md

> Swifty - https://getswifty.pro/
Free Offline Password Manager 
**Features**:
- Store Login/Password credentials
- Credit card Information 
- Secure notes to store sensitive information
- One-click Strong Password Generation
- Time-based One Time Passwords support (TOTP)
- Google Drive Sync (optional)
- No data is leaving your computer:
- Everything is encrypted, stored and decrypted on your local file system
- Decryption happens once on entering Master Password
- Ability to migrate from one computer to another using backup file or GDrive sync

Add Swifty

---

README.md

> AppFlowy - https://www.appflowy.io/
AppFlowy is an open-source alternative to Notion. You are in charge of your data and customizations. Built with Flutter and Rust.

Add AppFlowy

---

README.md

> YouTube Music Desktop - https://ytmdesktop.app/
A desktop client for YouTube Music.

Add YouTube Music Desktop

---

README.md

> NextDNS - https://nextdns.io/
NextDNS protects you from all kinds of security threats, blocks ads and trackers on websites and in apps and provides a safe and supervised Internet for kids — on all devices and on all networks.

Add NextDNS

---

README-zh.md
README.md

add Potplayer X

---

README-zh.md
README.md

BeMyEars is a system wide on-device live caption app …

Add BeMyEars

---

README.md

[Skiff](https://skiff.com/) offers end-to-end encrypted & decentralized email, real-time document collaboration, and file storage designed with zero-trust privacy

Add Skiff resources

---

README-zh.md
README.md

Add HTTPie APP

---

README.md

> Dissolv - https://www.7sols.com/dissolv/
The popular Hocus Focus app no longer works on macOS 12, this app does. It takes care of clearing away window clutter in the background as you work.

Add Dissolv

---

README.md

this tool improves productivity while allowing for a better way to utilize macOS's Globe key (aka fn key) input source switch functionality.
from the utility's description:
> macOS features a brilliant idea for the way to switch your keyboard's input source—the Globe key. While the idea is brilliant in design, in practice, however, the key is coded in a very intrusive and impractical way, which might prevent some users—especially those who tend to switch their input source often—from enjoying their overall user experience.
> 
> This utility completely reworks the way the Globe key functions and provides users with an improved overall user experience, and I sincerely hope that one day Apple is going to make it this way out-of-box. <...>

add betterglobekey

---

README-zh.md
README.md

1. InputSourcePro is a tool for multi-language users, it can change input languages when user switching different applications. 
If this is a relatively large or complex change, kick off the discussion by explaining why you chose …

Add InputSourcePro

---

README.md

Update Joplin link and delete Homebrew Cask

---

README.md

add apidog

---

README.md

1. Add Syntax Highlight and QLMarkdown in Quicklook plugin section.
2. Add qView, an image viewer application in Other Tools section.
3. Remove freeware icon from typora as it is no longer free now. ($14.99 with 15 days free trial)
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your …

Add Syntax Highlight, QLMarkdown and qView, Edit typora

---

README.md

1. Adding Ferdium, an open-source fork of Franz without paid restrictions.
nil

Add Ferdium

---

README.md

Hey guys wanted to add Mullvad VPN to the list. Its an awesome VPN service that is cheap and needs no account information to use!
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. …

Adding Mullvad VPN under Proxy and VPN Tools

---

README-zh.md
README.md

Adding a new app DisplayBuddy - which is a handy utility to control the brightness, contrast, input source, and other features of external displays directly from the Mac menu bar. (Website: https://displaybuddy.app)

Add DisplayBuddy

---

README-zh.md
README.md

The LaTeX app Texpad is now called Texifier. The unrelated app called "TextPad", a text editor for Windows, is available at [textpad.com](https://www.textpad.com/).
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to …

Update Textpad Name and Website

---

README-zh.md
README.md

[He3](https://he3.app/) is a free and modern developer utilities toolbox. It provides 200 builtin tools with more to come. It boost the productivity of developers in daily dev tasks with tools for formatting, generating, converting, encoding, etc.. It comes with convenient features including smart search, auto clipboard detection, hotkeys, custom themes, etc.
Here is a blog describing He3 in more details: https://he3.app/posts/announcement_en/ …

Add He3 App

---

README.md

1. Reeder 5 is not freeware, but it's on App Store so I changes the corresponding icon.

Update Reeder 5 icon tag

---

README.md

Correct "enabeling" to "enabling" in the description of `Hook for Mac`.

Fix a typo in the description of "Hook for Mac"

---

README-zh.md
README.md

[Elytra](https://elytra.app) is simple & private RSS feed reader with native rendering for
- text
- images
- videos 
It uses no web views and prevents tracking from tracking scripts and images when reading articles. 
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution …

Add Elytra.app

---

README.md

[Warp](https://www.warp.dev) is solid alternative to Alacritty, iTerm2, etc.,
It contains a lot of productivity-focused features, such as:
* AI Command Search
* Smart autocomplete
* Community + custom workflows
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did …

Add Warp Terminal

---

README.md

Remove spam link

---

README.md

[RemoveX](https://removex.io) - is an uninstaller tool for Mac computer. RemoveX has a beautifully UI using native design for MacOS.
We build RemoveX with a simple way to think, a simple way to use it and really focus on user requirements - uninstall an application as fast as possible.
User will not waste their money on features they do not need, do not understand, sometimes it is useless and rarely to use any more when making a comparison with other complex app.
Put an x in the boxes once …

Add RemoveX

---

README-zh.md
README.md

MiaoYan is a beautiful and elegant  free Markdown editor particularly built for Mac with Swift. It's just nice.
N/A

Add MiaoYan

---

README.md

Deeplink Buddy is a developer tool which helps me a lot in my job to manage deeplinks as a mobile engineer. As an engineer, I usually save all my deeplinks to Apple Notes, then whenever I want to run them, I have to copy and paste them to the terminal and run it. This takes many steps, and lots of them can be reduced. So this app helps you manage all deeplinks, and list out all available simulators so you can select the deeplink, then select the simulator, and press Run. Very simple and …

Add Deeplink Buddy

---

README-zh.md

Update WBIM Link

---

README.md

ILLA Cloud is an awesome open-source low-code tool for developers to use. It can speed up development with its pre-built-in components and database integrations. 
If this is a relatively large or complex change, kick off the …

ADD ILLA Cloud to Developer Utilities

---

README-zh.md
README.md

**I added Arc browser into the list as I realized this is probably one of the best browsers that I have used in my life. It is Mac exclusive now, and you have to join the waitlist to use it except for students who can get early access. But I still believe this is a great browser in terms of both usability and aesthetics. The "space" feature and the Spotlight-like search experience as well as easy access to …

Added Arc into the browser list.

---

README.md

I've added to the list [Sniffnet](https://github.com/GyulyVGC/sniffnet), an application to comfortably monitor network traffic written in Rust.
It also comes with a disk image installer for macOS, to make it easier to install also for the people who don't have Rust installed on their machines.
Documentation and further info can be found on the repository itself.

added Sniffnet to network analysis resources

---

README.md

**I've added to the list [ClipTools](https://macmost.com/cliptools), is a status menu application that gives you access to a variety of simple clipboard utilities from the right side of the menu bar.**
In addition to being able to access older clipboard contents, you can save clips, use powerful Smart Clips, paste the date or time in any format you wish, paste sample Lorem Ipsum text, type calculations and paste the result, or even calculate the result of a formula currently selected in text.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're …

Add ClipTools

---

README.md

Easier-to-understand wording.
N/A

Formatting and wording

---

README.md

This PR adds the "Clipboard" utility to the Clipboard Managers section where similar software is also located. However, unlike the other utilities, this one is entirely terminal-based, which makes it stand out from the others which all depend on the macOS GUI.

Add Clipboard to Clipboard Managers Section

---

README.md

1. Adding Folders - a file manager that is quite uniquely targeted at the users who recently transitioned from Windows to a Mac, and who would like to have a file manager similar to familiar Windows Explorer.
If this is a …

Add Folders File Manager

---

README.md

Looking to increase awareness of a fairly advanced and mature open source project that fully supports macOS.  If you agree it is an appropriate entry for the list, I appreciate the support.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. …

Add StargateDAW

---

README-zh.md

Update `README-zh.md`, only add `apptorrent` website. `README.md` already exists. While we shouldn't advocate or distribute pirated software, it might help some people.
No content.

add appstorrent to README-zh.md

---

README.md

Added Swift Quit - automatically quits apps when windows are closed.

Add SwiftQuit

---

README.md

Added Diffusion Bee - the easiest way to generate AI art... runs offline and no limits.

Add Diffusion Bee

---

README-zh.md
README.md

Add Outline

---

README.md

Added Affine - a modern, collaborative knowledge base.

Add Affine

---

README.md

Added Scrivener - the quintessential word processors for writers.

Add Scrivener

---

README-zh.md
README.md

1. Screen Studio is a screen recording tool, but it can directly add mouse tracking and ZoomIn ZoomOut effects to the recording without any editing (of course, it can also be edited manually) :).
2. OpenAI Translator is a cross-platform translation software based on the OpenAI API, which can achieve functions such as word translation, OCR, and vocabulary list on all platforms (including browsers) through selection. It is equivalent to Bob's cross-platform replacement.
Put an x in the boxes once …

Add screen studio and openai translator

---

README-zh.md
README.md

1. ⚡️ Lightning Fast. Starts in 2 seconds, optimized networking (35 Gbps) and disk, Rosetta x86 emulation.
2. 💨 Feather Light. Low CPU and disk usage, works with less memory, native Swift app, battery-friendly.
3. 🍰 Effortlessly Simple. Minimal setup, 2-way CLI integration & file access, VPN support and remote VS Code, SSH agent forwarding.
4. ⚙️ Powerful. Run seamless Docker containers, full Linux distros, and Kubernetes (soon). Robust networking with IPv6, ICMP, traceroute, and more.
Put an x …

Add OrbStack

---

README.md

Simple macOS menu bar application to view and interact with reminders. Developed with SwiftUI and using Apple Reminders as a source.
<div align="center">
<img
max-width="400"
width="45%"
src="https://github.com/DamascenoRafael/reminders-menubar/raw/master/images/reminder-menubar-light.png"
alt="Reminders MenuBar in light mode"
>
<img
max-width="400"
width="45%"
src="https://github.com/DamascenoRafael/reminders-menubar/raw/master/images/reminder-menubar-dark.png"
alt="Reminders MenuBar in dark mode"
>
</div>

Add Reminders MenuBar

---

README.md

Draw.io - Great open source diagramming program, which I've used to create the system architecture diagrams at my current job. 
OBS Studio - Best open source recording and live streaming program. Most YouTubers and streamers use this to create content. 
SurrealDB - Interesting open source database that is promising and in active development.  …

Add Draw.io, OBS Studio and SurrealDB

---

README-zh.md
README.md

1. Rectangle is a free and [Open Source](https://github.com/rxhanson/Rectangle) app that helps us to do window management.

Add rectangle app in window management category

---

README.md

Zotero is a free, easy-to-use tool to help you collect, organize, annotate, cite, and share your research sources.

Add Zotero

---

README.md

Adding [lo-rain](https://lo.cafe/lo-rain).
Adding [lo-rain](https://lo.cafe/lo-rain), a customization app that creates an aesthetic fully customizable rain over the desktop and other apps. It's a very pleasant effect that can help doing any kind of work.
None

Adding lo-rain

---

README.md

Get More details about the Issue here #1223 
The Issue is Fixed and able to merge.
N/A

Fix : Issue #1223

---

README.md

Hi,
I added Sidebar to the list. It's a modern Dock replacement for Mac. It adds a lot of convenient features that the standard Dock is missing.
Thanks for considering adding it to the list :)

Add Sidebar

---

README.md

[Removed a duplicate entry](https://github.com/jaywcjlove/awesome-mac/commit/cbb029f614d0850bcf7544ccccb17054b7284436#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L799) (was line 799) of the Arc browser in the README.md Browsers section, as [another entry already exists on line 786](https://github.com/jaywcjlove/awesome-mac/blob/f0555da6b6dcf2c806afb00fe1e7c6de0f3503d2/README.md?plain=1#L786) in the same section. `README-zh.md` was not changed as it [does not contain a duplicate entry](https://github.com/jaywcjlove/awesome-mac/blob/f0555da6b6dcf2c806afb00fe1e7c6de0f3503d2/R …

Remove Duplicate Arc Browser Entry

---

README.md

This application, in contrast with the current [ytmdesktop](https://github.com/ytmdesktop/ytmdesktop/issues/114), comes with a variety of **plugins** out-of-the-box, such as an: ad blocker, downloader, visualizer, audio compressor, and SponsorBlock support.

Add YouTube Music

---

README.md

Doughnut is a beautiful, open-source podcast client for Mac.

Add Doughnut (and Fix List Structure)

---

README-zh.md
README.md

This is a browser produced by Microsoft, which is very similar to the chrome browser. Not only can you use the same plugins as the chrome browser, but it also has more features that the chrome browser does not have, such as: vertical sidebar, split screen etc, it's also a good news for developers

Add Microsoft Edge Browser

---

README.md

- Remove duplicate Edge (added in #1233)
- Fix ungoogled-chromium link
- Add freeware icon to Orion
- Also: Edit Brave's OSS icon link to go directly to `/brave-browser` GitHub repo

Fix Browsers Section

---

README.md

One of the most popular web browsers in Russia.

Add Yandex

---

README.md

An open-source, multi-platform tool for quickly and easily encrypting your data.

Add Cryptomator

---

README.md

1. Add Jellyfin.
- [ x] I have read the CONTRIBUTING guide
- [ x] I have explained why this PR is important
- [ x] I have added necessary documentation (if appropriate)

Add Jellyfin.

---

README-zh.md
README.md

Rectangle entry should not be duplicated, Window management list should be sorted alphabetically
1. Removed a duplicate entry of Rectangle in the Window management section of [README.md](README.md) (kept newer entry)
1. Moved Rectangle entry to keep Window management list ordered alphabetically in both [README.md](README.md) and [README-zh.md](README-zh.md)
Fixes https://github.com/jaywcjlove/awesome-mac/issues/1253

Removed duplicate Rectangle entry, sorted alphabetically

---

README.md

The app lets your write in a minimal environments without any distractions. It also has a unique "brain dump mode" that helps you focus on writing. The app has 5/5 rating.

Add Plain Text Editor

---

README.md

Adds [pgMagic](https://pgmagic.app) - A new type of postgres client that lets you speak to your db in natural language and have generated SQL execute immediately.

Add pgMagic

---

README.md

[TextSniper](https://textsniper.app) is a simple macOS app that helps instantly extract text from anywhere (images, videos, PDFs, presentations, online meetings, etc.). Awards:  Editor’s Choice
If this is a relatively large or …

Add TextSniper

---

README.md

Application got removed, described under main page: http://jumpzero.com/frank/

Remove Frank DeLoupe

---

README.md

[Rize](https://rize.io/) is a time tracker tool which helps you in tracking every second of your time that you spend on you computer.
✅ New addition to the Productivity list
✅ I have read the CONTRIBUTING guide
✅ I have explained why this PR is important
✅ I have added necessary documentation (if appropriate)

Added "Rize" app to the Productivity list

---

README.md

Fixes https://github.com/jaywcjlove/awesome-mac/issues/1264

Update Termius description

---

README.md

I added PDFgear to the **Others** type in the **Reading and Writing Tools** catalog. PDFgear is a free PDF software with all the expected functions included, like view, edit, convert, OCR, annotate, page management, protection, etc. PDFgear is an excellent PDF software with a clean and straightforward interface so I added it to this list.  
2. If you're fixing a bug or resolving a feature request, be sure to …

Added PDFgear to the list

---

README.md

Add Pulp - audio sample manager.
Alternative to ADSR manager.
It's not important, but it's software that I'll continue to develop and make enjoyable for music designers.

Add Pulp - audio sample manager

---

README.md

QuikFlow is an innovative new app that allows users to create flowcharts with a mind-mapping workflow. Its workflow is similar to apps like MindNode, but it is not limited to a tree structure. It is the only app of its kind and strives to offer an easy and fast user-experience.
Disclaimer: I am one of the creators of QuikFlow.

Add QuikFlow

---

README.md

View the contents of a macOS installer package, *without* installing it first.

Add Suspicious Package

---

README.md

WezTerm is a powerful cross-platform terminal emulator and multiplexer implemented in Rust.

Add WezTerm

---

README.md

> If you're adding something to the list, be sure to explain why it should be added.
With the current Cambrian explosion in AI, interacting with AI on your Mac should be as easy as copy and paste. Parrotflow makes this possible. …

Add Parrotflow - Copilot for your Mac

---

README.md

Resolves #1206
The project is now actively [maintained](https://github.com/getstation/desktop-app/pull/184).

Add Station and alphabetize list

---

README-zh.md
README.md

Add Ryujinx

---

README.md

Removal of depreciated app. As the website states, it will no longer be supported in MacOS Sonoma.
None

Remove CheatSheet

---

README.md

- [x ] Fixing bug in existing item in list
Adding Mullvad: [@1292](https://github.com/jaywcjlove/awesome-mac/issues/1292) …

Update README with Mullvad.md

---

README.md

- Added two useful Apps
- Reordered list in Alphabetical order
- Fixed small typo for TigerVPN
None, it's a small PR.

README Update with 2 new apps + fixes

---

README.md

- Added two useful Apps (Virtualization + Backlight Shortcuts).
- Reorged Alphabetical order.
No further changes.

Added two new apps + reorg

---

README.md

- [ x ] New addition to list
Linear Mouse - Very helpful mouse tool. https://github.com/jaywcjlove/awesome-mac/issues/1278 …

Add Linear Mouse

---

README.md

1. Updating brackets github link

Update Brackets Github Link

---

README.md

- [ x ] New addition to list
https://github.com/jaywcjlove/awesome-mac/issues/1309 …

Add Saber 

---

README.md

Adding Simple Comic, a free open source eReader for graphic novels: files in .cbz, .cbr. and .pdf format. Also available in the Apple App Store. So far, the guide does not list any eReaders for graphic novels.

Add Simple Comic - eReader for graphic novels.

---

README-zh.md
README.md

change THORN description

---

README.md

- [x  ] New addition to list
https://github.com/jaywcjlove/awesome-mac/issues/1274 …

Add Default Folder X

---

README.md

Add MindMac to productivity section

---

README.md

Aspect is a photo organization application with support for peer-to-peer based synchronization across devices.
- [ x] I have read the CONTRIBUTING guide
- [ x] I have explained why this PR is important
- [ x] I have added necessary documentation (if appropriate)

Add Aspect photo organizer

---

README.md

Adds Journey Navigation, a new MacOS route planning app with weather along your route, turn-by-turn details, and much more.

Adds Journey Navigation route planner with weather along your route and more

---

README.md

Email Me is a native macOS, iOS and WatchOS to quickly email yourself stuff.

Adds Email Me to README.md

---

README.md

Add bruno api client

---

README.md

Canary Mail is my current and favorite email client and this i the reason i am proposing to add this. …

Add Canary Mail

---

README.md

Change the introduction to be easier to read, and have less/no grammatical errors.

Fixed Grammar, Made Text More Readable

---

README.md

I added Studio 3T. I think it deserves to be in the list since it is one of the most used MongoDB GUI client on Mac. It is an official partner of MongoDB as you can check out here: https://www.mongodb.com/partners/studio-3t

Added Studio 3T

---

README.md

BoltAI and PDF Pals are 2 **native** AI apps that does not charge a subscription. It's developed with great attention to details and follow the strict UI/UX of a native mac app.

Added BoltAI & PDF Pals

---

README-zh.md

iBar can be customized to hide and display, leaving the menu bar fresh and tidy in an instant! iBar also supports hiding the menu bar icon and displaying it in the aggregated floating window, greatly improving the use experience of the new Mac menu bar.

add iBar tool

---

README.md

I added **PaletteBrain** to the **Productivity** section.
PaletteBrain is a powerful and customizable ChatGPT application for Mac that lets you access the power of ChatGPT across all your Mac applications with the press of a shortcut.
If this is a …

Added PaletteBrain

---

README.md

Adding [Dropshare](https://dropshare.app) to file sharing section, since it is an established macOS app.
Disclaimer: I am the developer.

Add Dropshare to File Sharing

---

README.md

Macaify is a ChatGPT client that supports customizing different bots and their corresponding shortcuts, helping us quickly invoke ChatGPT with shortcuts in all locations. It greatly improves work efficiency.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're …

Add Macaify

---

README-zh.md
README.md

CleanClip is a super clean clipboard manager app. It can help us automatically record the copy history of the clipboard, avoiding important content being overwritten. I think CleanClip will greatly help us in our daily work.
CleanClip 是一个非常干净的剪贴板管理应用, 他可以帮助我们自动保存剪贴板的复制记录，避免重要内容被覆盖。也可以帮助我们在某些工作中提升工作效率。我想 CleanClip …

Add CleanClip

---

README-zh.md
README.md

YPlayer is a multifunctional app capable of generating subtitles in real-time locally, converting audio and video files into text for subtitle creation, transforming recordings into text, and translating subtitles, I believe it can help others.
BeMyEars English domain is too expensive to renew, so I change the domain.
Put …

Add YPlayer app and Fix BeMyEars english version URL

---

README-zh.md
README.md

add onmyzsh

---

README.md

Adding rancher desktop to Virtualization tab

---

README.md

Whisky is a new way to run Windows Games on MacOS using new Apple solution called Game Porting Toolkit.

Add Whisky

---

README.md

1. Added _Wokabulary_ to the app list. It is a flash card learning app for everybody learning a foreign language in school, evening class, or in self-study. Wokabulary is a native Mac app and also available for iPad and iPhone. It has been featured as App of the Day by Apple in September 2023.
2. Added a new category / section "Education" as Wokabulay did not seem to fit into any of the existing categories.

Add wokabulary

---

README.md

I have checked for other similar issues.
I have explained why this change is important.
I have added necessary documentation.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply …

Issue #1241 Add Zappy

---

README.md

Added CapsLockNoDelay, which is a useful utility that solves a great pain amongst fast typers.
There are many questions in stack overflow and such about how to solve this issue and this utility addresses this issue.

Added CapsLockNoDelay

---

README.md

Added OpenIn, as one of the applications for redirecting links to specific browsers (including Safari Profiles), and redirecting opening files in specific apps.

Add OpenIn

---

README.md

Adding new addition to the list. Unique app for storing your shellhistory in the database and sync via iCloud between macs

Add ShellHistory

---

README.md

Added Keyboard Cowboy, as a productivity app for macOS, enhancing user efficiency and control through customizable bindings for apps, shortcuts, automations, shell scripts, and more, in addition to keys rebindings.

adding Keyboard Cowboy app

---

README.md

Added Hyperkey and "Disk Drill"

---

README.md

Adding Lunatask which is a great all-in-one productivity and life-tracking app for Mac.

Add Lunatask

---

README.md

ZOC Terminal is very similar to SecureCRT which is already on the list. 
Thanks
I'm adding ZOC Terminal to the list.  It's a well known software similar to SecureCRT or iTerm2.  It's the only good TN3270 emulation on macOS and has received good ratings generally, e.g. …

Update README.md - ZOC Terminal

---

README.md

Add Zed to the list
Adding [Zed](https://zed.dev/) to the list because it is an awesome code editor!
If this is a relatively large or complex …

Update README.md to add Zed

---

README.md

1.Use blocklist instead of blacklist.

Use blocklist instead of blacklist

---

README.md

This is a duplication of an already existing app: BitBar has been rebooted as xBar. xBar is already present in the list …

Removed BitBar

---

README.md

**Proposed change(s):**
- Addition of Highlights to the list
Highlights is a research tool designed for researchers, with the ability to highlight, annotate and add images. 
**For more information:**
https://highlightsapp.net/tutorials/mac/
https://apps.apple.com/gb/app/highlights-pdf-reader-notes/id1498912833
https://9to5mac.com/2020/04/11/highlights-pdf-reader-universal-purchase/
https://apps.apple.com/gb/story/id1658435006 
1. If you're adding something to the list, be sure to explain why it …

Add Highlights

---

README-zh.md
README.md

Add GitMind

---

README.md

OSS part is just chromium, Frontend is at most source-available They even note it's not OSS in their website. Currently OSS icon is misleading.
https://help.vivaldi.com/desktop/privacy/is-vivaldi-open-source/
N/A

Vivaldi is not open-source

---

README.md

Added FunKey

---

README.md

[Assignee](https://assignee.app) is a simple, instant app switcher. No more mashing Command-Tab to switch to different apps, just assign a shortcut to an app and switch to it instantly
If this is a relatively large or complex …

Add Assignee

---

README.md

Added the app [Pie Menu](https://www.pie-menu.com), which with one keyboard shortcut triggers a different Radial Menus around your cursor based on which app is currently active.  Added under productivity.

Added Pie Menu to productivity tools

---

README.md

Add [RelaGit](https://rela.dev) to the list. It is a git GUI client with first-class support for macOS. …

Add RelaGit

---

README.md

[Spaced](https://sindresorhus.com/spaced) provides menu bar separators to group menu bar items for a more streamlined appearance. It is particularly beneficial on larger screens where menu bar space is ample, as opposed to smaller laptop screens with limited space.

Add Spaced

---

README.md

tl;dr A better AirDrop for links.
Hyperduck makes it super easy to send links from your iOS & visionOS devices to your Mac. For example, share a link from Safari on your iPhone, iPad, or Apple Vision Pro, and have it open in the default browser on your Mac moments later.
You can send a link even if your iOS/visionOS device and/or Mac is offline. The link will be sent and received the next time the devices are online. The link will never be lost.
My personal use-case is that I often discover cool stuff when I check Twitter on the go and I want to dig deeper into it later on my Mac. I have tried Instapaper, …

Add Hyperduck

---

README.md

AltTab is freeware

---

README.md

Website has been moved to a new domain.

Update SubManager website URL

---

README.md

The app lets you cut and paste files and folders in Finder using Command+X and Command+V. Without this app, you have to first copy (Command+C) and then remember to move (Option+Command+V).
https://sindresorhus.com/command-x

Add Command X

---

README.md

The app gives you instant access to your Mac’s camera feed for quick checks before video calls. Or just taking a quick photo.
https://sindresorhus.com/camera-preview

Add Camera Preview

---

README.md

You can use the app as a visual cue to stay motivated and manage time more efficiently.
https://sindresorhus.com/day-progress

Add Day Progress

---

README.md

The app lets you qickly access a monthly calendar from your menu bar. This should really have been built-in.
https://sindresorhus.com/menu-bar-calendar

Add Menu Bar Calendar

---

README-zh.md
README.md

移动一些文件到 Finder 其他目录或其他程序（比如 VS Code）, 依靠普通拖动需要调整好窗口，这些 app 可以解决这个痛点。
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, …

Add Dropshelf and Dropover

---

README.md

Aurora Editor is a text editor / ide, opensource.

Add Aurora Editor

---

README.md

The app helps you actually get stuff done by focusing on a single task at a time.
https://sindresorhus.com/one-task

Add One Task

---

README.md

The app makes it super simple to jot down some quick notes that are always visible on your desktop.
https://sindresorhus.com/memo-widget

Add Memo Widget

---

README.md

It can be useful to show one more clock in the menu bar.
https://sindresorhus.com/second-clock

Add Second Clock

---

README.md

The app lets Mac app developers easily preview how their macOS app icon will look in the Dock and how your menu bar item icon will appear. It updates automatically on changes.
https://sindresorhus.com/icon-preview

Add Icon Preview

---

README.md

Added Freeter - the free and open-source organizer for a smarter work on your computer. …

Add Freeter

---

README.md

Update Open-Source Software: xonsh,xxh,x-cmd

---

README.md

Add Applite app. Applite is an open source GUI client for Homebrew that aims to bring the convenience of Homebrew casks to the non-technical user.
Key features of Applite:
-  Install, update, and uninstall apps with a single click
- Clean and simple UI designed for non-technical users
- Free and open source
- Works with existing brew installation
- Supports system proxy (HTTP, HTTPS, and SOCKS5)
- Handpicked gallery of awesome apps
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. …

Add Applite

---

README-zh.md

add 123云盘，并将百度云改成百度网盘

---

README.md

Add Pixen, the premium pixel art and animation editor for the Mac. It is a native AppKit Mac app which has been around for over 10 years in the Mac App Store and has 4.8 stars in the U.S. App Store.

Add Pixen to list

---

README.md

Add Archimedes, a native Markdown editor for macOS with inline LaTeX support. It is a native AppKit Mac app with Quick Look integration, a handwriting recognition feature for Magic Trackpad users, and more. …

Add Archimedes

---

README-zh.md
README.md

**"Web Serve"** is a simple and easy-to-use application designed for quickly setting up and managing local static servers, suitable for a variety of use cases. Whether you are a developer, designer, content creator, or a regular user, this application can bring you significant convenience and efficiency.

Add `Web Serve`

---

README-zh.md
README.md

Add `SafeInCloud` to the Chinese list. fixed #1434

---

README-zh.md
README.md

2. If you're fixing a bug or resolving a feature request, be sure to link to that issue.
[Dataflare](https://dataflare.app) is a simple, fast, and visually appealing database client/SQL editor that supports dozens of databases, with a small size of less than 20MB. …

Add Dataflare

---

README-zh.md
README.md

Remove ClashX fixed #1477

---

README-zh.md
README.md

Add `Quick RSS`

---

README-zh.md

Add CodeEdit: A Native Mac Edito 
and fix some bugs

Add CodeEdit: A Native Mac Editor

---

README-zh.md

Add FDM 和 AnimacX 删除QQ输入法

---

README.md

added life note, a great ai journaling app.
If this is …

Added life note, a great ai journaling app where you can journal with the greatest minds in history. 

---

README.md

Zed is OSS now, adding the link to the repository

Update Zed with OSS link

---

README-zh.md

add pap.er

---

README.md

The current URL makes it hard to locate the RerouteMe app. Please update it to https://nadenco.gumroad.com/l/rerouteme. …

fix: update the erroneous link for RerouteMe

---

README.md

Atomic - Habits Tracker is the best app to help you build good habits, break bad ones, and stay on top of your daily routines. Atomic will give you everything you need to transform your habits into lasting, positive changes. Help you to become a better version of yourself.
Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are …

Add Atomic - Habits Tracker app

---

README.md

Marker Data, a unique application meticulously crafted for Final Cut Pro users seeking seamless Marker extraction, conversion, and database creation capabilities. Marker Data optimises the way professionals manage Marker’s metadata within Final Cut Pro projects. With its intuitive interface and robust feature set, Marker Data simplifies the extraction process while ensuring the utmost accuracy in representing Marker’s metadata. Marker Data offers a multitude of use cases, including creation of …

Add Marker Data

---

README.md

**Selectric**
Selectric is a private personal search engine for your email and documents across your local computer and all your online accounts. We built it because we got tired of wasting time everyday trying to keep track of information both at work and outside. 
We built Selectric with privacy as a core principle. All data we index is stored only on your local computer and we also run AI models for search and summarization locally. No data ever leaves your …

Added Selectric to Productivity section

---

README.md

Zellij is a modern replacement for tmux, with much saner config and amazing UX.

Add Zellij

---

README-zh.md
README.md

This macOS app enhances the Finder context menu by providing additional functionalities that streamline user workflows. With improved accessibility to frequently used actions, users can perform tasks more efficiently without navigating through multiple menus. The app introduces customizable options, allowing users to tailor their experience according to their specific needs. By integrating this tool, users will benefit from a more productive and enjoyable Finder experience.

Add RClick

---

README.md

Adding my own app since it's awesome 😁. It allows you to move/resize a window without having to click on it, just pressing a shortcut and moving your mouse. It also allows you to get the same behaviors as some linux desktops (left click to move, right click to resize).

Add Swift Shift app

---

README.md

Adding [Collate](https://collate.one/get-started)  - organize, summarize and query PDFs offline, completely private and free.

Update README.md to add Collate

---

README.md

Adding Tauri to list of Frameworks For Hybrid Applications. Tauri is alternative to Electron that is based on Rust. It is gaining on popularity in recent times due to it's performance compared to other hybrid app developing frameworks.

Add Tauri to Frameworks For Hybrid Applications

---

README.md

Visual Studio for Mac has been retired

---

README.md

Notchnook is included in the list for its ability to adapt the Mac menu bar to the notch, offering seamless integration and practical customization options. It's a must-have tool for enhancing both aesthetics and functionality on modern MacBooks.
If this is a relatively large or complex change, kick off the discussion by explaining why you …

Add NotchNook

---

README.md

Add BeagleEditor (READ THE DESCRIPTION CAREFULLY!)

---

README.md

Added missing periods in various parts of the text to ensure consistency and correctness in writing style. This revision maintains uniform formatting throughout the document, improves readability, and aligns the punctuation with the rest of the content for a more polished and structured appearance.
Put an x in the boxes …

Added missing periods for consistency and correctness

---

README.md

this url returns a 403 error
If this is a relatively …

remove Sip - 403 error

---

README.md

- Updated the Setapp and Table Plus Descriptions. Table Plus is no longer open source but included in the Setapp subscription.
/

Update Setapp and Table Plus

---

README.md

[Azure Data Studio](https://azure.microsoft.com/en-us/products/data-studio) has been [retired](https://techcommunity.microsoft.com/blog/azuresqlblog/azure-data-studio-retirement/4371009).
N/A

Remove retired Azure Data Studio

---

README.md

It's hard to find video editing software that supports macOS and is open-source. I've made software that can edit keyframes and I think it will help other developers or users.

Add Nugget

---

README.md

Remove Velja free label, It is currently priced at $8 in Appstore.
No similar submission has been submitted before.
Remove Velja free label, It is currently priced at $8 in Appstore.
- [x ] I have read the CONTRIBUTING guide
- [x ] I have explained why this PR is important
- [x ] I have added necessary documentation (if appropriate)

Update README.md for Velja

---

README.md

Proposing to add TrailBase to the list of DataBases. It's an easy to use and open FireBase alternative. It's easy to build, has native Mac arm & intel releases, and docker releases.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, …

Add TrailBase to Databases.

---

README.md

https://github.com/glinford/dns-easy-switcher …

Add DNS Easy Switcher

---

README.md

Add SteerMouse to the "System Related Tools" section.
"SteerMouse is a utility that lets you freely customize buttons, wheels and cursor speed. Both USB and Bluetooth mice are supported."
It's a great app for configuring mice/trackballs! …

Add SteerMouse to the "System Related Tools" section

---

README-zh.md
README.md

Adding [Swads.app](https://swads.app/). A modern, native, and intuitively redesigned Synology Download Station client. Built with Swift for macOS 15+ and iOS/iPadOS 18+, it offers blazing-fast performance, up to 7x faster QuickConnect, seamless multi-instance management, detailed task insights, and advanced settings control. Plus, enjoy features like NAS overview, QuickConnect Data Center, user quota, push notifications, iCloud sync, and more. …

Add Swads.app

---

README.md

The industry standard CLI for working with JSON Schema. Supports macOS. Open-source, written in C++, released under the AGPL.

Add the JSON Schema CLI

---

README.md

TimeScribe is an appealing addition to the awesome-mac list because it offers a minimalist yet effective approach to time tracking. The app’s intuitive design allows users to easily record their work hours without any unnecessary complications, operating entirely offline and without the need for sign-ups or registrations. This not only enhances the user experience but also ensures a higher level of privacy. 
Additionally, as an open-source and completely free tool, TimeScribe serves as a refreshing alternative to many time tracking apps that lock essential features behind subscription paywalls. Its focus on simplicity, accessibility, and privacy makes it a valuable asset for anyone looking to manage their …

Add TimeScribe

---

README-zh.md
README.md

Terminal--electerm and Clipboard--iCopy

---

README.md

1. Mac Mouse Fix is awesome tool and It fixes the mouse scroll direction issue and the tool is open source
2. It supports Mac's newer Apple silicon hardware architecture. No need to install Rosetta. Barely consumes 20MB of RAM.
If …

Add Mac Mouse Fix #1611

---

README.md

**What types of changes does your PR introduce?** 
Unread is an RSS reader with beautiful typography and a variety of color themes. Unread is available for Mac, iPhone, and iPad. The app support feed services like Feedbin, Feedly, Fever, Inoreader, NewsBlur, Unread cloud along side local usage.
While apps like reeder 5 have deprecated its support, Unread is a perfect replacement for enjoyable reading.
Link to the app -[Unread](https://www.goldenhillsoftware.com/unread/)

Added Unread RSS reader

---

README.md

Add [Tuneful](https://www.tuneful.dev) to the list. "Control your Spotify and Apple Music from the notch, menu bar or mini player."

Add Tuneful

---

README.md

The app lets you switch your Magic Mouse, Keyboard and Trackpad between multiple Macs with different Apple IDs. It saves users time by exposing simple menu bar icons and keyboard shortcuts that allow the user to transfer the connection of their peripheral from one Mac to the other. The app is completely offline and uses bluetooth to communicate between Macs.
https://magic-switch.com

Add Magic Switch

---

README.md

Added [Lunacy](https://icons8.com/lunacy) under the Design Tools section.
**Why this is important:**
Lunacy is a high-quality, actively maintained vector graphic design tool that works offline, supports real-time collaboration, and includes a library of built-in assets. It’s completely free with a solid feature set, making it a great alternative to paid tools like Figma or Sketch.

Add Lunacy to Design Tools

---

README.md

add Tailscale
If this is a relatively large or complex …

add Tailscale

---

command-line-apps-zh.md
command-line-apps.md

Add mdctl - a command-line tool for processing Markdown files

---

README-zh.md
README.md

Add MacMusicPlayer to the list of music players

---

README.md

Aerospace is a popular new tiling window manager for macOS.

Add Aerospace (#1599)

---

README-zh.md

added tailscale with CN description in README-zh.md

---

README.md

1. I'm adding Free Download Manager (FDM) to the list of download utilities. FDM is a highly popular and widely used download manager known for its robust features, ease of use, and cross-platform compatibility. It supports accelerating downloads, resuming broken downloads, torrents, and video downloading, making it a comprehensive solution for many users. Its active development and strong user base warrant its inclusion in this curated list.

Add Free Download Manager

---

README-zh.md

This PR adds saga-reader, an AI-driven think tank-style reader that automatically retrieves information from the internet based on user-specified topics and preferences. It uses cloud or local large models to summarize and provide guidance, and it includes an AI-driven interactive companion reading function, allowing you to discuss and exchange ideas with AI about the content you've read.
Thanks for taking your time!
https://github.com/sopaco/saga-reader
Saga Reader is an AI-driven think tank-style reader that automatically retrieves information from the internet based on user-specified topics and preferences. It uses cloud or local large models to summarize and provide guidance, and it includes an AI-driven interactive companion reading function, allowing you to discuss and exchange …

Add "Saga Reader" to awesome-mac

---

README-zh.md

remove bitbar & update Xbar's description. Tell people xbar is a new bitbar.
BitBar is Deprecated and it had been deleted from the English version, I deleted BitBar from the Chinese verison and updated the Description of XBar.

remove bitbar

---

README.md

Add KubeSwitch

---

README.md

Adding my FOSS tool as it has become relatively popular and has received positive feedback.  …

Add DockDoor

---

README.md

Added Testpiler, a free, native Mac for converting unit tests from the Swift XCTest framework to Swift Testing.

Add Testpiler

---

README.md

Add Runtime

---

README.md

1. InputSourcePro is now FOSS (Free and Open Source Software)

Update InputSourcePro to mark it as FOSS
